In [3]:
import numpy as np
import pandas as pd

**Dropping the Extra columns ('Unnamed: 0.2','Unnamed: 0','Unnamed: 0.1') from the DataFrame.**

In [4]:
df = pd.read_csv('All cities.csv')

In [5]:
df.drop(['Unnamed: 0.2','Unnamed: 0','Unnamed: 0.1'],axis = 1,inplace = True,)

In [6]:
df['Total Fee'] = df['Fee at clinic'] + df['Online Fee']

# Checking null values

In [7]:
df.isnull().sum()

Name                         0
Specialization               0
Experience (in years)      173
Education                  285
Fee at clinic              769
Online Fee                1197
Clinic Name                602
Area                       603
Recently Consulted for    2012
Available From             120
Available Till             120
City                         0
Total Fee                 1521
dtype: int64

In [8]:
# checking total null rows of clinic name and area

df[df['Clinic Name'].isnull() | df['Area'].isnull()]  # 603

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Recently Consulted for,Available From,Available Till,City,Total Fee
1,Dr. Pioneer Scans,Dentist,24.0,"BDS, MDSPioneer Scans , Kolkat",NaN,NaN,NaN,NaN,NaN,9:00 AM,2:00 PM,Kolkata,NaN
12,Dr. Subhadeep Raha,Dentist,26.0,Advanced Aesthetics,₹ 300,NaN,NaN,NaN,NaN,10:30 AM,9:00 PM,Kolkata,NaN
16,Dr. Anuran Ghosh Mondal,Dentist,11.0,BDS,₹ 250,₹ 200,NaN,NaN,NaN,11:00 AM,8:00 PM,Kolkata,₹ 250₹ 200
29,Dr. Trisha Ghosh,Dentist,13.0,"BDS, MDS - Orthodontics",₹ 500,NaN,NaN,NaN,"Root Canal Treatment, Root canal, Dental CareN...",4:00 PM,6:00 PM,Kolkata,NaN
53,Dt. Pratyasha Agrawal,Dietitian/Nutritionist,44.0,"MD - Skin & VD, MBBS, DVD",NaN,NaN,NaN,NaN,NaN,10:00 AM,12:00 PM,Kolkata,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2902,Dr. Jiva Ayurveda,Ayurveda,26.0,BAMS,₹ 299,NaN,NaN,NaN,"Acne Treatment, Hair Loss, Flu",10:00 AM,7:00 PM,Bangalore,NaN
2909,Dr. Gowthaman Krishnamoorthy,Ayurveda,23.0,"Bachelor of Ayurveda, Medicine and Surgery (BAMS)",₹ 500,₹ 500,NaN,NaN,"Pain Treatment, Yoga, Kshar Sutra",7:00 AM,7:00 PM,Bangalore,₹ 500₹ 500
2910,Dr. Gokulan Bg,Ayurveda,37.0,Bachelor of Ayurveda Medicine and Surgery (BAM...,₹ 200,₹ 300,NaN,NaN,"Acne Scars Treatment, Staying Healthy, Ayurved...",2:00 PM,5:00 PM,Bangalore,₹ 200₹ 300
2942,Dr. Chaya,Ayurveda,18.0,"BAMS, MSc - Yoga, MSc - Psychotherapy And Coun...",NaN,NaN,NaN,NaN,NaN,2:00 PM,7:00 PM,Bangalore,NaN
2949,Dr. Roopakala Nayak,Ayurveda,16.0,"Bachelor of Ayurveda, Medicine and Surgery (BAMS)",₹ 200,₹ 200,NaN,NaN,NaN,2:00 PM,5:00 PM,Bangalore,₹ 200₹ 200

In [9]:
# checking total null rows of clinic name and area and education
df[df['Clinic Name'].isnull() | df['Area'].isnull() | df['Education'].isnull()]  # 780

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Recently Consulted for,Available From,Available Till,City,Total Fee
1,Dr. Pioneer Scans,Dentist,24.0,"BDS, MDSPioneer Scans , Kolkat",NaN,NaN,NaN,NaN,NaN,9:00 AM,2:00 PM,Kolkata,NaN
12,Dr. Subhadeep Raha,Dentist,26.0,Advanced Aesthetics,₹ 300,NaN,NaN,NaN,NaN,10:30 AM,9:00 PM,Kolkata,NaN
16,Dr. Anuran Ghosh Mondal,Dentist,11.0,BDS,₹ 250,₹ 200,NaN,NaN,NaN,11:00 AM,8:00 PM,Kolkata,₹ 250₹ 200
25,Dr. Neha Banerjee,Dentist,NaN,NaN,₹ 300,₹ 200,Smile,Kolkata,Root canalNext,10:00 AM,9:00 PM,Kolkata,₹ 300₹ 200
29,Dr. Trisha Ghosh,Dentist,13.0,"BDS, MDS - Orthodontics",₹ 500,NaN,NaN,NaN,"Root Canal Treatment, Root canal, Dental CareN...",4:00 PM,6:00 PM,Kolkata,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2910,Dr. Gokulan Bg,Ayurveda,37.0,Bachelor of Ayurveda Medicine and Surgery (BAM...,₹ 200,₹ 300,NaN,NaN,"Acne Scars Treatment, Staying Healthy, Ayurved...",2:00 PM,5:00 PM,Bangalore,₹ 200₹ 300
2928,Ayur Jagruti Clinic,Ayurveda,NaN,NaN,₹ 300,₹ 300,Ayur Jagruti Ayurveda Clinic,Indira Nagar,NaN,2:00 PM,4:00 PM,Bangalore,₹ 300₹ 300
2935,Ayur Jagruti Clinic,Ayurveda,NaN,NaN,₹ 300,₹ 300,Ayur Jagruti Ayurveda Clinic,Indira Nagar,NaN,2:00 PM,4:00 PM,Bangalore,₹ 300₹ 300
2942,Dr. Chaya,Ayurveda,18.0,"BAMS, MSc - Yoga, MSc - Psychotherapy And Coun...",NaN,NaN,NaN,NaN,NaN,2:00 PM,7:00 PM,Bangalore,NaN
2949,Dr. Roopakala Nayak,Ayurveda,16.0,"Bachelor of Ayurveda, Medicine and Surgery (BAMS)",₹ 200,₹ 200,NaN,NaN,NaN,2:00 PM,5:00 PM,Bangalore,₹ 200₹ 200

In [10]:
df.columns

Index(['Name', 'Specialization', 'Experience (in years)', 'Education',
       'Fee at clinic', 'Online Fee', 'Clinic Name', 'Area',
       'Recently Consulted for', 'Available From', 'Available Till', 'City',
       'Total Fee'],
      dtype='object')

In [11]:
# null count

df[df['Fee at clinic'].isnull()] # 769

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Recently Consulted for,Available From,Available Till,City,Total Fee
1,Dr. Pioneer Scans,Dentist,24.0,"BDS, MDSPioneer Scans , Kolkat",NaN,NaN,NaN,NaN,NaN,9:00 AM,2:00 PM,Kolkata,NaN
53,Dt. Pratyasha Agrawal,Dietitian/Nutritionist,44.0,"MD - Skin & VD, MBBS, DVD",NaN,NaN,NaN,NaN,NaN,10:00 AM,12:00 PM,Kolkata,NaN
54,Dt. Mayanka Singhal,Dietitian/Nutritionist,30.0,"MD (AIIMS), Clinical Fellow, Skin Oncology (Ne...",NaN,NaN,NaN,NaN,"Pimples, Pimples Treatment, Acne / Pimples Tre...",11:00 AM,4:00 PM,Kolkata,NaN
58,Dt. Souvick Dey,Dietitian/Nutritionist,38.0,"MBBS, MD - Dermatology, Venereology & Leprosy",NaN,NaN,NaN,NaN,"Pimples, Pimples Treatment, Acne / Pimples Tre...",11:00 AM,4:30 PM,Kolkata,NaN
59,Dt. Tapasi Hazra,Dietitian/Nutritionist,20.0,"MBBS, MD - Dermatology , Venereology & Leprosy...",NaN,₹ 500,Woodlands Multispeciality Hospital - Alipur,Alipore,NaN,7:00 PM,8:00 PM,Kolkata,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2896,Dr. Mili Chakraborty,Psychologist,7.0,"MA - Psychology, Diploma in Personal Councelli...",NaN,₹ 500,Aria clinic,Haralur Road,NaN,10:00 AM,7:00 PM,Bangalore,NaN
2897,Ms. Ramitha Ramesh,Psychologist,7.0,M A Clinical Psychology,NaN,NaN,NaN,NaN,NaN,11:00 AM,6:00 PM,Bangalore,NaN
2898,Ms. Seema Pradhan,Psychologist,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2:00 PM,3:30 PM,Bangalore,NaN
2899,Mr. Gangaram Prem Kumar,Psychologist,11.0,Diploma in Counselling,NaN,₹ 500,TSMS,Bang,NaN,NaN,NaN,Bangalore,NaN
2942,Dr. Chaya,Ayurveda,18.0,"BAMS, MSc - Yoga, MSc - Psychotherapy And Coun...",NaN,NaN,NaN,NaN,NaN,2:00 PM,7:00 PM,Bangalore,NaN

In [12]:
df[df['Online Fee'].isnull()]  # 1197

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Recently Consulted for,Available From,Available Till,City,Total Fee
0,Dr. Kaustubh Das,Dentist,22.0,"BDS, MFDS RCPS(Glasgow), FFD RCS (IRE)",₹ 500,NaN,ASPIRE CLINIC,Kolkata,NaN,10:00 AM,7:00 PM,Kolkata,NaN
1,Dr. Pioneer Scans,Dentist,24.0,"BDS, MDSPioneer Scans , Kolkat",NaN,NaN,NaN,NaN,NaN,9:00 AM,2:00 PM,Kolkata,NaN
9,Dr. Supratim Chanda,Dentist,21.0,BDS,₹ 500,NaN,Chanda Dental Clinic,Shyambazar,NaN,12:00 PM,6:30 PM,Kolkata,NaN
11,Dr. Kashif Ahmed Shamsi,Dentist,11.0,Internationally Certified Practitioner for Cle...,₹ 200,NaN,DentRelief Dental Clinic,Chittaranjan Avenue,"Teeth Whitening, Teeth CleaningNext",5:00 PM,9:00 PM,Kolkata,NaN
12,Dr. Subhadeep Raha,Dentist,26.0,Advanced Aesthetics,₹ 300,NaN,NaN,NaN,NaN,10:30 AM,9:00 PM,Kolkata,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2931,Dr. Aparna Kulkarni,Ayurveda,13.0,"MD - Ayurveda, Bachelor of Ayurveda, Medicine ...",₹ 200,NaN,Dr Kulkarni's Ayur Clinic,Uttarahalli,NaN,7:00 AM,7:00 AM,Bangalore,NaN
2932,Dr. M Rahul,Ayurveda,12.0,"BAMS, Fellowship In Neurological Rehabilitatio...",₹ 500,NaN,Angsana Ayurveda,Rajanukunte,NaN,10:00 AM,8:00 PM,Bangalore,NaN
2933,Dr. Umme Salma,Ayurveda,13.0,"Bachelor of Ayurveda, Medicine and Surgery (BAMS)",₹ 60,NaN,SSHIRADI SAI CLINIC,Murugeshpalya,NaN,5:00 PM,9:30 PM,Bangalore,NaN
2937,Dr. Mini Nair,Ayurveda,29.0,"DSM ( Siddha Medicine), BAMS",₹ 200,NaN,Ayur Healing Ayurveda And Siddha Hospital,Koramangala,"Siddha, Difficulty Sleeping, Diabetes",10:00 AM,6:00 PM,Bangalore,NaN
2942,Dr. Chaya,Ayurveda,18.0,"BAMS, MSc - Yoga, MSc - Psychotherapy And Coun...",NaN,NaN,NaN,NaN,NaN,2:00 PM,7:00 PM,Bangalore,NaN

In [13]:
df[df['Online Fee'].isnull() | df['Fee at clinic'].isnull()]  # 1521

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Recently Consulted for,Available From,Available Till,City,Total Fee
0,Dr. Kaustubh Das,Dentist,22.0,"BDS, MFDS RCPS(Glasgow), FFD RCS (IRE)",₹ 500,NaN,ASPIRE CLINIC,Kolkata,NaN,10:00 AM,7:00 PM,Kolkata,NaN
1,Dr. Pioneer Scans,Dentist,24.0,"BDS, MDSPioneer Scans , Kolkat",NaN,NaN,NaN,NaN,NaN,9:00 AM,2:00 PM,Kolkata,NaN
9,Dr. Supratim Chanda,Dentist,21.0,BDS,₹ 500,NaN,Chanda Dental Clinic,Shyambazar,NaN,12:00 PM,6:30 PM,Kolkata,NaN
11,Dr. Kashif Ahmed Shamsi,Dentist,11.0,Internationally Certified Practitioner for Cle...,₹ 200,NaN,DentRelief Dental Clinic,Chittaranjan Avenue,"Teeth Whitening, Teeth CleaningNext",5:00 PM,9:00 PM,Kolkata,NaN
12,Dr. Subhadeep Raha,Dentist,26.0,Advanced Aesthetics,₹ 300,NaN,NaN,NaN,NaN,10:30 AM,9:00 PM,Kolkata,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2931,Dr. Aparna Kulkarni,Ayurveda,13.0,"MD - Ayurveda, Bachelor of Ayurveda, Medicine ...",₹ 200,NaN,Dr Kulkarni's Ayur Clinic,Uttarahalli,NaN,7:00 AM,7:00 AM,Bangalore,NaN
2932,Dr. M Rahul,Ayurveda,12.0,"BAMS, Fellowship In Neurological Rehabilitatio...",₹ 500,NaN,Angsana Ayurveda,Rajanukunte,NaN,10:00 AM,8:00 PM,Bangalore,NaN
2933,Dr. Umme Salma,Ayurveda,13.0,"Bachelor of Ayurveda, Medicine and Surgery (BAMS)",₹ 60,NaN,SSHIRADI SAI CLINIC,Murugeshpalya,NaN,5:00 PM,9:30 PM,Bangalore,NaN
2937,Dr. Mini Nair,Ayurveda,29.0,"DSM ( Siddha Medicine), BAMS",₹ 200,NaN,Ayur Healing Ayurveda And Siddha Hospital,Koramangala,"Siddha, Difficulty Sleeping, Diabetes",10:00 AM,6:00 PM,Bangalore,NaN
2942,Dr. Chaya,Ayurveda,18.0,"BAMS, MSc - Yoga, MSc - Psychotherapy And Coun...",NaN,NaN,NaN,NaN,NaN,2:00 PM,7:00 PM,Bangalore,NaN

In [14]:
df[df['Online Fee'].isnull() & df['Fee at clinic'].isnull()]  #445

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Recently Consulted for,Available From,Available Till,City,Total Fee
1,Dr. Pioneer Scans,Dentist,24.0,"BDS, MDSPioneer Scans , Kolkat",NaN,NaN,NaN,NaN,NaN,9:00 AM,2:00 PM,Kolkata,NaN
53,Dt. Pratyasha Agrawal,Dietitian/Nutritionist,44.0,"MD - Skin & VD, MBBS, DVD",NaN,NaN,NaN,NaN,NaN,10:00 AM,12:00 PM,Kolkata,NaN
54,Dt. Mayanka Singhal,Dietitian/Nutritionist,30.0,"MD (AIIMS), Clinical Fellow, Skin Oncology (Ne...",NaN,NaN,NaN,NaN,"Pimples, Pimples Treatment, Acne / Pimples Tre...",11:00 AM,4:00 PM,Kolkata,NaN
58,Dt. Souvick Dey,Dietitian/Nutritionist,38.0,"MBBS, MD - Dermatology, Venereology & Leprosy",NaN,NaN,NaN,NaN,"Pimples, Pimples Treatment, Acne / Pimples Tre...",11:00 AM,4:30 PM,Kolkata,NaN
61,Dt. Smriti Bhalotia,Dietitian/Nutritionist,34.0,"MBBS, MD - Dermatology",NaN,NaN,NaN,NaN,"Pimples, Hair Loss, Hair Loss TreatmentNext",11:00 AM,7:00 PM,Kolkata,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2892,Mr. Mahesh Natarajan,Psychologist,NaN,NaN,NaN,NaN,NaN,NaN,Behaviour and Thought Problems,NaN,NaN,Bangalore,NaN
2895,Dr. Ravisankar Av,Psychologist,11.0,"Ph..D., M.Sc (Psy.), PG Diploma In Guidance an...",NaN,NaN,NaN,NaN,NaN,9:00 AM,1:30 PM,Bangalore,NaN
2897,Ms. Ramitha Ramesh,Psychologist,7.0,M A Clinical Psychology,NaN,NaN,NaN,NaN,NaN,11:00 AM,6:00 PM,Bangalore,NaN
2898,Ms. Seema Pradhan,Psychologist,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2:00 PM,3:30 PM,Bangalore,NaN
2942,Dr. Chaya,Ayurveda,18.0,"BAMS, MSc - Yoga, MSc - Psychotherapy And Coun...",NaN,NaN,NaN,NaN,NaN,2:00 PM,7:00 PM,Bangalore,NaN

In [15]:
df[df['Experience (in years)'].isnull()]

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Recently Consulted for,Available From,Available Till,City,Total Fee
25,Dr. Neha Banerjee,Dentist,NaN,NaN,₹ 300,₹ 200,Smile,Kolkata,Root canalNext,10:00 AM,9:00 PM,Kolkata,₹ 300₹ 200
41,Deepshikha Chowdhury,Dentist,NaN,NaN,₹ 500,₹ 250,Dr. Deepshikha Chowdhury Multispeciality Denta...,Beliaghata,NaN,4:00 PM,7:00 PM,Kolkata,₹ 500₹ 250
67,Dt. Seema Poddar,Dietitian/Nutritionist,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7:00 AM,9:00 PM,Kolkata,NaN
70,Dt. Soumi Sinha,Dietitian/Nutritionist,NaN,NaN,₹ 250,NaN,Dr. Paul's Advanced Hair And Skin Solutions – ...,Kolkata,NaN,11:00 AM,7:15 PM,Kolkata,NaN
80,Dr. Madhurima Roy,Dietitian/Nutritionist,NaN,NaN,₹ 700,₹ 400,Medithics Clinic (On Call),Mukundapur,NaN,10:00 AM,2:30 PM,Kolkata,₹ 700₹ 400
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2891,Ms. Tamanna Chaudhary,Psychologist,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10:00 AM,6:00 PM,Bangalore,NaN
2892,Mr. Mahesh Natarajan,Psychologist,NaN,NaN,NaN,NaN,NaN,NaN,Behaviour and Thought Problems,NaN,NaN,Bangalore,NaN
2898,Ms. Seema Pradhan,Psychologist,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2:00 PM,3:30 PM,Bangalore,NaN
2928,Ayur Jagruti Clinic,Ayurveda,NaN,NaN,₹ 300,₹ 300,Ayur Jagruti Ayurveda Clinic,Indira Nagar,NaN,2:00 PM,4:00 PM,Bangalore,₹ 300₹ 300
2935,Ayur Jagruti Clinic,Ayurveda,NaN,NaN,₹ 300,₹ 300,Ayur Jagruti Ayurveda Clinic,Indira Nagar,NaN,2:00 PM,4:00 PM,Bangalore,₹ 300₹ 300

# checking duplicates

In [16]:
df[df.duplicated()]

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Recently Consulted for,Available From,Available Till,City,Total Fee
670,Dr. Kedar Ghatnekar,Ayurveda,16.0,"Bachelor of Ayurveda, Medicine and Surgery (BAMS)",₹ 200,₹ 200,Saptarshee Clinics,Shukrawar peth,NaN,4:00 PM,8:00 PM,Pune,₹ 200₹ 200
671,Dr. Lalta Prasad,Ayurveda,55.0,"MS, Bachelor of Ayurveda, Medicine and Surgery...",₹ 200,NaN,Sushruta Clinic,sangvi,ComaNext,7:00 PM,8:00 PM,Pune,NaN
680,Dr. K D,Ayurveda,15.0,"Bachelor of Ayurveda, Medicine and Surgery (BA...",₹ 300,₹ 200,Maheshwar Clinic,Pune,"Gaining Weight, Hair Loss, Leg Pain",10:00 AM,5:00 PM,Pune,₹ 300₹ 200
682,Dr. Avinash Deore,Ayurveda,20.0,"MD, BAMS",₹ 200,NaN,Shree Sai Ayurvedic Panchakarma Clinic &Infert...,Pimpri,NaN,5:00 PM,9:00 PM,Pune,NaN
692,Dr. Pankaj Nahata,Ayurveda,14.0,BAMS,₹ 100,₹ 300,Shree Vishwamani Ayurvedic Clinic & Panchakarm...,Bibwewadi,"Premature Ejaculation, Weight Loss, Dark Circle",5:00 PM,9:00 PM,Pune,₹ 100₹ 300
693,Dr. Dipti Kapare,Ayurveda,19.0,"BAMS, MSC In Counselling, Certificate of Prani...",NaN,NaN,NaN,NaN,NaN,6:00 PM,8:30 PM,Pune,NaN
694,Dr. Vikas Chothe,Ayurveda,10.0,"MD - Ayurveda, FIIM, MD",₹ 200,NaN,Vikas Chothe,Chinchwad,NaN,9:00 AM,9:00 PM,Pune,NaN
1111,Dr. Sandeep Madaan,Ayurveda,21.0,MD - Ayurveda,₹ 300,₹ 300,Aastha Ayurveda Clinic,Rohini,"Sex Education, Diabetes, Female Hair LossNext",6:00 PM,9:00 PM,Delhi,₹ 300₹ 300
1112,Dr. Namadhar Sharma,Ayurveda,40.0,"BAMS, MD - Ayurveda",₹ 200,₹ 600,Prem Adhar Research Institute And Hospital,Rohini,NaN,11:00 AM,2:00 PM,Delhi,₹ 200₹ 600
1120,Monga Medi Clinic,Ayurveda,24.0,"Bachelor of Ayurveda, Medicine and Surgery (BAMS)",₹ 800,₹ 300,Dr Monga Medi Clinic - Lajpat Nagar,Lajpat Nagar,NaN,9:30 AM,8:30 PM,Delhi,₹ 800₹ 300
1121,Dr. Manu Rajput,Ayurveda,14.0,"Diploma in Body Therapy, England, PG Diploma i...",NaN,NaN,NaN,NaN,"Acne/Pimples, Hair Loss, Acne Scars",11:00 AM,2:00 PM,Delhi,NaN
1131,Dr. D.S . Rathi,Ayurveda,45.0,"Bachelor of Ayurveda, Medicine and Surgery (BAMS)",₹ 500,₹ 300,Deepak Ayurvedic Centre,Shahdara,Weight Management,11:00 AM,2:00 PM,Delhi,₹ 500₹ 300
1132,Dr. Ashutosh Sharma,Ayurveda,21.0,"Bachelor of Ayurveda, Medicine and Surgery (BAMS)",₹ 200,₹ 350,Shiv Shakti Chikitsalaya,Karol Bagh,NaN,4:00 PM,8:00 PM,Delhi,₹ 200₹ 350
1133,Dr. Ashish Sharma,Ayurveda,18.0,"Bachelor of Ayurveda, Medicine and Surgery (BAMS)",₹ 500,₹ 500,Arogyam Ayurveda,Paschim Vihar,NaN,9:00 AM,7:00 PM,Delhi,₹ 500₹ 500
1141,Dr. Mamta Kumari,Ayurveda,14.0,"Bachelor of Ayurveda, Medicine and Surgery (BA...",₹ 500,₹ 300,Jyoti Memorial Jain Hospital,Najafgarh,NaN,11:00 AM,2:00 PM,Delhi,₹ 500₹ 300
1142,Usma Ayurvedic Clinic,Ayurveda,41.0,"Bachelor of Ayurveda, Medicine and Surgery (BAMS)",₹ 500,₹ 300,Usma Ayurvedic Clinic,Laxmi Nagar,NaN,9:00 AM,8:00 PM,Delhi,₹ 500₹ 300
1143,Dr. Vaidic Chikitsa,Ayurveda,47.0,"Bachelor of Ayurveda, Medicine and Surgery (BAMS)",₹ 300,₹ 200,Vaidic Chikitsa,Delhi,"Sex Education, Weight Loss, Hair LossNext",10:00 AM,6:00 PM,Delhi,₹ 300₹ 200
1310,Dr. Dayanand Dhekane,General+Physician,16.0,MD - Internal Medicine,₹ 400,NaN,Shiva speciality Clinic,Mumbai,NaN,6:30 PM,9:30 PM,Mumbai,NaN
1441,Dr. Archana Prabhu,Gynaecologist,30.0,"MBBS, DGO, MD - Obstetrics & Gynaecology",NaN,NaN,NaN,NaN,"No Periods, Painful Periods, PregnancyNext",7:30 PM,9:00 PM,Mumbai,NaN
1530,Ms. Prachi Tripathi,Psychologist,12.0,NaN,NaN,NaN,NaN,NaN,NaN,12:00 PM,8:30 PM,Mumbai,NaN
1541,Ms. Vidisha Gadre,Psychologist,7.0,M.A.,₹ 800,₹ 300,Healing & Feeling,Mulund,NaN,8:00 AM,11:00 PM,Mumbai,₹ 800₹ 300
1542,Dr. Iti Shukla,Psychologist,9.0,MA clinical psychology,₹ 500,₹ 500,Mind-space,Goregaon West,NaN,12:00 PM,3:00 PM,Mumbai,₹ 500₹ 500
1570,Dr. Praveen Dube,Ayurveda,26.0,BAMS,₹ 200,₹ 50,DR. PRAVEEN D. DUBE,Santacruz East,NaN,10:00 AM,1:30 PM,Mumbai,₹ 200₹ 50
1582,Dr. Rani Suresh Thondikulam,Ayurveda,31.0,"BAMS, PGDCDM",₹ 500,₹ 300,Bodyveda Ayurvedic Wellness Centre,Andheri West,NaN,12:00 PM,8:00 PM,Mumbai,₹ 500₹ 300
1583,Dt. Seemaa J Poddar,Ayurveda,16.0,"Diploma in Clinical Nutrition, Sport Nutrition...",NaN,₹ 350,Ms. Seemaa j Poddar's Practice,Goregaon East,NaN,2:00 PM,6:00 PM,Mumbai,NaN
1586,Dr. Deepika Solge,Ayurveda,16.0,"Bachelor of Ayurveda, Medicine and Surgery (BAMS)",₹ 500,₹ 300,Nature villa,Mumbai,"Asthma, Pimples TreatmentNext",10:00 AM,1:00 PM,Mumbai,₹ 500₹ 300
1597,Dr. D.S.Nikam,Ayurveda,11.0,MD - Ayurveda,₹ 500,NaN,NaN,NaN,Weight LossNext,9:00 AM,5:00 PM,Mumbai,NaN
1598,Dr. Anay Davare,Ayurveda,13.0,MD - Ayurveda,₹ 300,₹ 400,Siddhant Ayurvedi & Panchkarma Clinic,Mumbai,NaN,10:00 AM,1:00 PM,Mumbai,₹ 300₹ 400
2021,Dr. Sindhu V,Ayurveda,5.0,"MD-Siddha, BSMS, MD-Siddha, BSMS",₹ 250,₹ 200,Siddha 365 Health Care,Villivakkam,NaN,10:00 AM,9:30 PM,Chennai,₹ 250₹ 200
2030,Dr. Mohamed Rizwan N,Ayurveda,NaN,NaN,₹ 200,₹ 300,Riz Heal Natural Health Care & Research Centre,Chennai,NaN,10:00 AM,1:00 PM,Chennai,₹ 200₹ 300
2031,Dr. M Harikrishnan,Ayurveda,14.0,MD(Ayurveda),₹ 100,₹ 300,Dr Hari's Samhita Ayurvedashala,West Mambalam,NaN,7:00 PM,9:00 PM,Chennai,₹ 100₹ 300
2032,Dr. K T Jayakrishnan,Ayurveda,38.0,"Bachelor of Ayurveda, Medicine and Surgery (BAMS)",₹ 300,₹ 350,Shanta Ayurveda Hospital,T.Nagar,NaN,4:00 PM,6:00 PM,Chennai,₹ 300₹ 350
2190,Ms. Naba Farooqui,Dietitian/Nutritionist,6.0,"Masters (MSc) - Nutrition and Dietetics, BSc -...",₹ 600,NaN,Nourish by Naba Farooqui,Banjara Hills,NaN,NaN,NaN,Hyderabad,NaN
2480,Dr. Sushma Shivkumar M,Ayurveda,14.0,BAMS,₹ 700,₹ 250,Swami Clinic,Yousufguda,NaN,9:00 AM,1:00 PM,Hyderabad,₹ 700₹ 250
2481,Dr. Vijay Kumar G,Ayurveda,24.0,"Bachelor of Ayurveda, Medicine and Surgery (BA...",₹ 500,₹ 500,Ayucure clinic,Hyderabad,NaN,10:00 AM,7:00 PM,Hyderabad,₹ 500₹ 500
2499,Dr. N. Subrahmanyam,Ayurveda,10.0,"BAMS, MA",₹ 500,₹ 500,Amrutham Ayurveda Hospital,Hyderabad,NaN,10:30 AM,2:00 PM,Hyderabad,₹ 500₹ 500
2590,Dr. Srinivas C,Dermatologist,26.0,"M D, MBBS MD",₹ 400,NaN,Revive Skin & Hair Clinic(Vidyaranyapura),Vidyaranyapura,"Acne/Pimples, Pimples TreatmentNext",12:30 PM,4:00 PM,Bangalore,NaN
2790,Dr. Rekha,Gynaecologist,22.0,"MBBS, DGO",₹ 200,NaN,Elite Hospital,Attibele,NaN,7:00 AM,11:00 PM,Bangalore,NaN
2920,Dr. A V Lohit,Ayurveda,19.0,"BAMS, MD - Ayurveda Medicine, Postgraduate Dip...",₹ 600,NaN,Dr. Lohit's Ayur Sex Clinic,Basaveshwara Nagar,"Male Sexual Problems Treatment, Erection Probl...",11:00 AM,2:00 PM,Bangalore,NaN
2921,Dr. Arun B Jain,Ayurveda,22.0,"MD, Bachelor of Ayurveda, Medicine and Surgery...",₹ 100,₹ 150,SUKRUTHA Ayurvedic Center,Banashankari,DiabetesNext,4:00 PM,8:30 PM,Bangalore,₹ 100₹ 150
2922,Dr. Manasa Bhat,Ayurveda,13.0,"Bachelor of Ayurveda, Medicine and Surgery (BAMS)",₹ 300,₹ 350,Tatkshana Ayurveda Hospital,Yeshwanthpur,NaN,4:00 PM,6:45 PM,Bangalore,₹ 300₹ 350
2931,Dr. Aparna Kulkarni,Ayurveda,13.0,"MD - Ayurveda, Bachelor of Ayurveda, Medicine ...",₹ 200,NaN,Dr Kulkarni's Ayur Clinic,Uttarahalli,NaN,7:00 AM,7:00 AM,Bangalore,NaN
2932,Dr. M Rahul,Ayurveda,12.0,"BAMS, Fellowship In Neurological Rehabilitatio...",₹ 500,NaN,Angsana Ayurveda,Rajanukunte,NaN,10:00 AM,8:00 PM,Bangalore,NaN
2935,Ayur Jagruti Clinic,Ayurveda,NaN,NaN,₹ 300,₹ 300,Ayur Jagruti Ayurveda Clinic,Indira Nagar,NaN,2:00 PM,4:00 PM,Bangalore,₹ 300₹ 300
2943,Dr. Anuja Marawar,Ayurveda,24.0,"Bachelor of Ayurveda, Medicine and Surgery (BA...",₹ 350,₹ 300,Keva Ayurveda Whitefield,Whitefield,NaN,3:30 PM,6:00 PM,Bangalore,₹ 350₹ 300
2945,Dr. Navaneetha Krishna K,Ayurveda,18.0,BAMS,₹ 500,₹ 300,AV Multispeciality Hospital,Banashankari,NaN,10:00 AM,8:00 PM,Bangalore,₹ 500₹ 300
2946,Dr. Vijay Laxmi Singh,Ayurveda,4.0,"Bachelor of Ayurveda, Medicine and Surgery (BAMS)",₹ 400,₹ 500,Ayurganic,Electronic City,NaN,10:30 AM,8:00 AM,Bangalore,₹ 400₹ 500

In [17]:
df[df['Name'] == 'Dr. Navaneetha Krishna K']

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Recently Consulted for,Available From,Available Till,City,Total Fee
2936,Dr. Navaneetha Krishna K,Ayurveda,18.0,BAMS,₹ 500,₹ 300,AV Multispeciality Hospital,Banashankari,NaN,10:00 AM,8:00 PM,Bangalore,₹ 500₹ 300
2945,Dr. Navaneetha Krishna K,Ayurveda,18.0,BAMS,₹ 500,₹ 300,AV Multispeciality Hospital,Banashankari,NaN,10:00 AM,8:00 PM,Bangalore,₹ 500₹ 300

In [18]:
df[df['Name'] == 'Dr. Lalta Prasad']

Empty DataFrame
Columns: [Name, Specialization, Experience (in years), Education, Fee at clinic, Online Fee, Clinic Name, Area, Recently Consulted for, Available From, Available Till, City, Total Fee]
Index: []

# Dropping duplicate values

In [19]:
df.drop_duplicates(inplace = True)

# dropping recently consulted columns

In [20]:
df.drop(columns = ['Recently Consulted for'], inplace = True)

In [21]:
df.isnull().sum()

Name                        0
Specialization              0
Experience (in years)     171
Education                 282
Fee at clinic             764
Online Fee               1182
Clinic Name               597
Area                      598
Available From            119
Available Till            119
City                        0
Total Fee                1505
dtype: int64

In [22]:
df.drop(columns = ['Total Fee'],inplace = True)

In [23]:
df

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Available From,Available Till,City
0,Dr. Kaustubh Das,Dentist,22.0,"BDS, MFDS RCPS(Glasgow), FFD RCS (IRE)",₹ 500,NaN,ASPIRE CLINIC,Kolkata,10:00 AM,7:00 PM,Kolkata
1,Dr. Pioneer Scans,Dentist,24.0,"BDS, MDSPioneer Scans , Kolkat",NaN,NaN,NaN,NaN,9:00 AM,2:00 PM,Kolkata
2,Dr. Asif Naushad,Dentist,19.0,"House Surgeon, House Surgeon, House Surgeon, BDS",₹ 300,₹ 300,JM DENTAL,Kolkata,10:00 AM,9:00 PM,Kolkata
3,Dr. Prabhjeet Singh Sethi,Dentist,24.0,Certified Implantologist,₹ 500,₹ 350,Dontia Dental Care,Kolkata,3:00 PM,8:00 PM,Kolkata
4,Dr. Dibyendu Dutta,Dentist,30.0,"Certified Implantologist, Advanced Aesthetics,...",₹ 300,₹ 500,Smilz Dental Treatment Facility,www.smilz.net,11:00 AM,1:00 PM,Kolkata
...,...,...,...,...,...,...,...,...,...,...,...
2942,Dr. Chaya,Ayurveda,18.0,"BAMS, MSc - Yoga, MSc - Psychotherapy And Coun...",NaN,NaN,NaN,NaN,2:00 PM,7:00 PM,Bangalore
2944,Dr. Sumedha K A,Ayurveda,11.0,"BAMS, M.D Panchakarma",₹ 300,₹ 200,Shathayu Ayurveda clinic,AECS Layout,9:00 AM,7:30 PM,Bangalore
2947,Dr. Prema Jyothi Fraser,Ayurveda,8.0,MD,₹ 200,₹ 200,Sri Mahima Multispecality Homoeo Clinic,Jayanagar,5:00 PM,8:30 PM,Bangalore
2948,Dr. Kavya Kadapi Kossambe,Ayurveda,6.0,MD - Ayurveda,₹ 300,₹ 300,Kaya chikitsalaya,ISRO Layout,10:00 AM,1:00 PM,Bangalore
2949,Dr. Roopakala Nayak,Ayurveda,16.0,"Bachelor of Ayurveda, Medicine and Surgery (BAMS)",₹ 200,₹ 200,NaN,NaN,2:00 PM,5:00 PM,Bangalore

# filling nan values in online fee and offline fee

In [24]:
df['Fee at clinic'].fillna('₹ 0',inplace = True)

In [25]:
df['Online Fee'].fillna('₹ 0',inplace = True)

In [26]:
df.isnull().sum()

Name                       0
Specialization             0
Experience (in years)    171
Education                282
Fee at clinic              0
Online Fee                 0
Clinic Name              597
Area                     598
Available From           119
Available Till           119
City                       0
dtype: int64

In [27]:
df['Online Fee'].unique()

array(['₹ 0', '₹ 300', '₹ 350', '₹ 500', '₹ 400', '₹ 125', '₹ 100',
       '₹ 200', '₹ 599', '₹ 250', '₹ 600', '₹ 900', '₹ 800', '₹ 150',
       '₹ 499', '₹ 850', '₹ 399', '₹ 550', '₹ 50', '₹ 99', '₹ 161',
       '₹ 95', '₹ 999', '₹ 700', '₹ 750', '₹ 349', '₹ 450', '₹ 90',
       '₹ 299', '₹ 829', '₹ 310', '₹ 223', '₹ 650', '₹ 170', '₹ 180',
       '₹ 30', '₹ 10', '₹ 380', '₹ 249', '₹ 1', '₹ 51', '₹ 149', '₹ 199',
       '₹ 120', '₹ 680'], dtype=object)

In [28]:
df['Fee at clinic'].unique()

array(['₹ 500', '₹ 0', '₹ 300', '₹ 400', '₹ 450', '₹ 200', '₹ 250',
       '₹ 600', '₹ 150', '₹ 800', '₹ 100', '₹ 850', '₹ 900', '₹ 350',
       '₹ 700', '₹ 650', '₹ 40', '₹ 330', '₹ 550', '₹ 950', '₹ 990',
       '₹ 699', '₹ 750', '₹ 999', '₹ 299', '₹ 669', '₹ 50', '₹ 1', '₹ 44',
       '₹ 45', '₹ 34', '₹ 56', '₹ 530', '₹ 499', '₹ 509', '₹ 11', '₹ 325',
       '₹ 60'], dtype=object)

In [29]:
df[df['Fee at clinic'] == '₹ 50']

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Available From,Available Till,City
1101,Dr. Vijay Abbot,Ayurveda,50.0,Graduate in Ayurvedic Medicine and Surgery ( G...,₹ 50,₹ 50,Hakim Hari Kishan Lal Clinic,Patel Nagar,12:00 PM,4:00 PM,Delhi
1102,Hakim Hari Kishan Lal Clinic,Ayurveda,50.0,Sexual Health Clinic,₹ 50,₹ 50,Hakim Hari Kishan Lal Clinic,Patel Nagar,12:00 PM,4:00 PM,Delhi
1107,Dr. Mahesh Shah,Ayurveda,55.0,"Bachelor of Ayurveda, Medicine and Surgery (BAMS)",₹ 50,₹ 50,Hakim Hari Kishan Lal Clinic,Patel Nagar,12:00 PM,4:00 PM,Delhi
1158,Dr. M.M / Zmrajani,Dentist,16.0,"M.D , B.D.S , FWCEF , FWCEF , F.A.G.E., BDS, ...",₹ 50,₹ 0,₹ 4,000 onlineSt.Mother Teresa Dental Hospital,10:00 AM,9:00 PM,Mumbai
1301,Dr. Vivek Trivedi,General+Physician,5.0,"Bachelor of Medicine, Bachelor of Surgery (M.B...",₹ 50,₹ 100,NaN,NaN,10:00 AM,2:00 PM,Mumbai
1644,Dr. Ohm Nijandhan.K,Dentist,11.0,BDS,₹ 50,₹ 0,Stunning Smiles Dental & Hearing Aid Clinic,Thirumangalam,10:00 AM,7:00 PM,Chennai

In [30]:
for i in df['Clinic Name'] :
    if type(i) == str :
        if i[0] == '₹' :
            print(i)

₹ 1
₹ 1
₹ 1
₹ 1
₹ 1
₹ 1
₹ 1
₹ 1
₹ 1
₹ 2
₹ 1
₹ 1
₹ 1
₹ 1
₹ 1
₹ 1
₹ 1
₹ 1
₹ 1
₹ 3
₹ 1
₹ 1
₹ 1
₹ 1
₹ 1
₹ 1
₹ 3
₹ 1
₹ 4
₹ 1
₹ 1
₹ 1
₹ 1
₹ 1
₹ 3
₹ 1
₹ 1
₹ 1
₹ 1
₹ 1
₹ 4
₹ 3
₹ 1
₹ 3
₹ 1
₹ 1
₹ 1
₹ 1
₹ 7
₹ 1
₹ 1
₹ 1
₹ 1
₹ 1
₹ 5
₹ 1
₹ 6
₹ 1
₹ 1
₹ 1
₹ 3
₹ 6
₹ 1
₹ 2
₹ 1
₹ 1
₹ 1

In [31]:
for i in df['Area'] :
    if type(i) == str :
        if i[0] == '0' :
            print(i)

000 onlineInskin Clinic
000 onlineSucharita Sengupta
000 onlineHealth care nursing home
000 onlineMeditips
000 onlineCounselling Clinic
000 onlineSiddhi Clinic
000 onlineKemps Skin Clinic
000 onlineAyushman Hospital
000 onlineHealth Mania - Rohini
000 onlineTHINKYOU.IN
000 onlineDr Rakesh Sharma’s Clinic
000 onlineDr Sabyasachi Das Clinic ( Samalka )
000 onlinePatel Hospital
000 onlineDr Indira's Clinic
000 onlineSatyam Medical Centre
000 onlineArora's Homeopathic Clinic
000 onlineDr Shailesh Jain's Clinic
000 onlineKarnik Dental Clinic
000 onlineSt.Mother Teresa Dental Hospital
000 onlineDermAvenue Advanced Skin & Hair Clinic
000 onlineDr.Pallavi Sule's SKIN| HAIR |AESTHETICS
000 onlineDr Manjiri Bhusaris Mojo Mrakle Centre
000 onlineHealthy U
000 onlineinji healthcare
000 onlineorthospine centre and physio rehab care
000 onlineDr Fatema Ebrahim OPD
000 onlineImPerfect
000 onlineakatalyst
000 onlineGurukrupa Ayurvedic Clinic
000 onlineDr V. Sethuraman Clinic
000 onlineNUTRIGENEDIETS
000 onlineSri Singhvi Health Center- Purasaiwakkam
000 onlineMind Re-store Psychological Testing & Counselling Centre
000 onlineThe Mind Care Center For Mental Health
000 onlineWisdom Counseling Psychotherapy Centre
000 onlineJAYAM HEALTH CENTRE
000 onlineDr. Nithyasri Ayurveda  Clinic
000 onlineRadiance Skin Hair Cosmetic & Obstetrics And Gynaecology Center
000 onlineDr. Vimala's Skin
000 onlineVernon Skin And Hair Clinic
000 onlineUltra wellness
000 onlineDr. P Sharat Kumar
000 onlineEVA Care Clinic- The Every Woman?s Clinic
000 onlineSri Sai Super Speciality Ayurvedic Clinic
000 onlineDr. Raj's Centre For Skin And Hair
000 onlineTricho - Derma Hair and Skin Speciality
000 onlineAvance Derma Skin
000 onlineTrustwell Hospitals
000 onlineJeevottama Health

In [32]:
df[df['City'] == 'Kolkata'].iloc[60:120]

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Available From,Available Till,City
60,Dt. Samapti Maity,Dietitian/Nutritionist,13.0,"MBBS, MD - Dermatology , Venereology & Leprosy...",₹ 800,₹ 0,₹ 1,500 onlineApollo Gleneagles Hospitals,10:00 AM,4:00 PM,Kolkata
61,Dt. Smriti Bhalotia,Dietitian/Nutritionist,34.0,"MBBS, MD - Dermatology",₹ 0,₹ 0,NaN,NaN,11:00 AM,7:00 PM,Kolkata
62,Dt. Meena Gupta,Dietitian/Nutritionist,13.0,"MBBS, MD - Dermatology, Fellowship in Dermatos...",₹ 600,₹ 0,₹ 1,000 onlineInskin Clinic,10:00 AM,7:30 PM,Kolkata
63,Dt. Kalpana Roy,Dietitian/Nutritionist,16.0,Dermatology Backed Expert Skin & Hair Care Sol...,₹ 500,₹ 0,NaN,NaN,NaN,NaN,Kolkata
64,Dt. Juhi Mimani,Dietitian/Nutritionist,15.0,"MBBS, MD - Dermatology , Venereology & Leprosy",₹ 500,₹ 400,Medica Superspecialty Hospital,E.M Bypass,6:00 PM,7:00 PM,Kolkata
65,Dr. Ananya Bhowmik,Dietitian/Nutritionist,19.0,"MD - Dermatology, Trichologist",₹ 600,₹ 0,NaN,NaN,10:00 AM,10:00 PM,Kolkata
66,Dt. Shruti Kejriwal,Dietitian/Nutritionist,20.0,"MBBS, MD - MD- Skin & VD",₹ 500,₹ 0,Dr. KULDEEP SINGH SKIN HAIR CLINIC & AMERICAN ...,Kalikapur,5:30 PM,7:00 PM,Kolkata
67,Dt. Seema Poddar,Dietitian/Nutritionist,NaN,NaN,₹ 0,₹ 0,NaN,NaN,7:00 AM,9:00 PM,Kolkata
68,Ms. Priyangee Lahiry,Dietitian/Nutritionist,23.0,"MBBS, MD - Dermatology, Fellowship in Cosmetic...",₹ 0,₹ 0,NaN,NaN,12:30 PM,6:30 PM,Kolkata
69,Dr. Nidhi Prakash,Dietitian/Nutritionist,17.0,Trichologist,₹ 100,₹ 300,NaN,NaN,10:00 AM,8:00 PM,Kolkata
70,Dt. Soumi Sinha,Dietitian/Nutritionist,NaN,NaN,₹ 250,₹ 0,Dr. Paul's Advanced Hair And Skin Solutions – ...,Kolkata,11:00 AM,7:15 PM,Kolkata
71,Dr. Sucharita Sengupta,Dietitian/Nutritionist,13.0,"MD - Dermatology, Fellowship in dermatosurgery...",₹ 450,₹ 0,Eleganz Skin & Hair Clinic,Dhakuria,10:00 AM,1:00 PM,Kolkata
72,Dt. Sangita Mondal,Dietitian/Nutritionist,6.0,"BNYS, FMC (Fellow in Med.Cosmetology), PG Dipl...",₹ 300,₹ 250,MIRAKEL SKIN & BEAUTY CLINIC,Kolkata,10:30 AM,2:00 PM,Kolkata
73,Dt. Poonam,Dietitian/Nutritionist,28.0,MD,₹ 100,₹ 500,Manoranjan Homoeo Hall,Thakurpukur,10:00 AM,6:00 PM,Kolkata
74,Dt. Nikita Mitra,Dietitian/Nutritionist,14.0,"MBBS, MD - Dermatology",₹ 500,₹ 600,Nova Medical Services,Kolkata,3:00 PM,5:00 PM,Kolkata
75,Dt. Sanchita Shaw,Dietitian/Nutritionist,24.0,MD,₹ 400,₹ 500,Ghosh Clinique,Kolkata,6:00 PM,7:00 PM,Kolkata
76,Dt. Ritu. Nandi,Dietitian/Nutritionist,49.0,"MBBS, MD - Dermatology",₹ 800,₹ 0,Skin and Hair Clinic,Kolkata,12:00 PM,1:00 PM,Kolkata
77,Dt. Monalisa Das,Dietitian/Nutritionist,5.0,"MBBS, MD, DNB, FRGUHS",₹ 800,₹ 600,Narayana Multispeciality Hospital,Jessore Road,10:00 AM,1:00 PM,Kolkata
78,Dt. Sneha Majumder,Dietitian/Nutritionist,25.0,MBBS-DVD-PhD,₹ 350,₹ 300,Nebula Skin Clinic,Kolkata,10:00 AM,1:00 PM,Kolkata
79,Surabhi Banerjee,Dietitian/Nutritionist,11.0,"MD - Dermatology, MBBS",₹ 600,₹ 500,La Derma Skin & Hair Clinic,Salt Lake,9:00 AM,7:00 PM,Kolkata
80,Dr. Madhurima Roy,Dietitian/Nutritionist,NaN,NaN,₹ 700,₹ 400,Medithics Clinic (On Call),Mukundapur,10:00 AM,2:30 PM,Kolkata
81,Dt. Anubha Taparia Saraogi,Dietitian/Nutritionist,25.0,MD - MD- Skin & VD,₹ 800,₹ 300,The Calcutta Medical Research Institute,Kolkata,11:00 AM,2:00 PM,Kolkata
82,Dt. Sudeshna Banerjee,Dietitian/Nutritionist,28.0,"MBBS, MD - Dermatology",₹ 700,₹ 0,Wizderm Speciality Skin & Hair Clinic,Kolkata,9:00 AM,12:00 PM,Kolkata
83,Mrs. Anuradha Chowdhary,Dietitian/Nutritionist,19.0,"MBBS, MD - Dermatology",₹ 400,₹ 0,Dr. Bhattacharyya's Skin And Physio Clinic,Salt Lake,8:00 PM,9:00 PM,Kolkata
84,Dt. Snehal Kochar,Dietitian/Nutritionist,37.0,"MBBS, MD - Dermatology",₹ 0,₹ 0,NaN,NaN,11:30 AM,3:00 PM,Kolkata
85,Dt. Pallavi Majumder,Dietitian/Nutritionist,46.0,"MBBS, DGO, Diploma in Venerology and Dermatology",₹ 700,₹ 0,Royd Skin Hair And Laser Center,Kolkata,2:00 PM,5:00 PM,Kolkata
86,Dt. Ankita Das,Dietitian/Nutritionist,24.0,MD,₹ 500,₹ 500,Dr. Indrajit Bahali,Kolkata,12:00 PM,5:00 PM,Kolkata
87,Dt. Jayita Brahmo,Dietitian/Nutritionist,18.0,"MBBS, DNB - Dermatology & Venereology",₹ 800,₹ 0,PR DIAGNOSTICS & POLYCLINIC,Dum Dum,6:00 PM,7:00 PM,Kolkata
88,Dt. Munmun Pradhan,Dietitian/Nutritionist,5.0,"MD - Dermatology (Gold medalist), MBBS (Hons.)",₹ 800,₹ 350,Dr. Vohra's Skin Clinic,Elgin,3:00 PM,5:00 PM,Kolkata
89,Dr. Joydeep Roy,Dietitian/Nutritionist,42.0,MD,₹ 300,₹ 500,K V C Clinic,Kolkata,7:30 PM,9:30 PM,Kolkata
90,Dt. Sonal Surekha,Dietitian/Nutritionist,NaN,NaN,₹ 250,₹ 250,"Dr. Paul""s Advanced Hair & Skin Solutions",Kolkata,11:00 AM,6:00 PM,Kolkata
91,Dt. Jayita Kundu,Dietitian/Nutritionist,42.0,"MBBS, DDV",₹ 200,₹ 200,Spandan Medical,Kolkata,7:00 PM,9:00 PM,Kolkata
92,Ms. Jyoti Pachisia,Dietitian/Nutritionist,14.0,"MD Dermatology, Fellow of cutaneous and laser ...",₹ 600,₹ 200,Apex Institute of Medical Sciences,Survey Park,6:30 PM,7:30 PM,Kolkata
93,Dt. Suman Santra,Dietitian/Nutritionist,20.0,MD - Dermatology,₹ 500,₹ 300,Floss,Kolkata,6:00 PM,8:00 PM,Kolkata
94,Ms. Ashmita Biswas,Dietitian/Nutritionist,10.0,MBBS Bachelor of Medicine and Bachelor of Surg...,₹ 0,₹ 0,NaN,NaN,11:00 AM,7:00 PM,Kolkata
95,Mr. Soumam Dutta,Dietitian/Nutritionist,30.0,md,₹ 300,₹ 0,Dr. Partha Sarathi Sen's Clinic,Dum Dum Park,7:30 PM,9:00 PM,Kolkata
96,Dt. Chandrima Saha,Dietitian/Nutritionist,27.0,"MBBS, MD - Skin & VD",₹ 700,₹ 0,Alura Aesthetic Clinic and Diagnostics,Bangur Avenue,6:00 PM,7:00 PM,Kolkata
97,Dt. Hema Gandhi,Dietitian/Nutritionist,45.0,"MBBS, MD - Dermatology",₹ 0,₹ 0,NaN,NaN,10:30 AM,12:30 PM,Kolkata
98,Dr. Minakshi Dutta,Dietitian/Nutritionist,26.0,"MBBS, MD - Dermatology",₹ 500,₹ 0,Pristine,Kolkata,4:00 PM,6:00 PM,Kolkata
99,Dt. Anuradha Sharma,Dietitian/Nutritionist,2.0,"MBBS,MD ( DVL)",₹ 600,₹ 400,Datta's Dermatology Clinic,Garia,8:30 AM,10:00 AM,Kolkata
100,Dr. Md Abdullah Asghar,General+Physician,29.0,B.Sc. - Dietitic,₹ 0,₹ 0,NaN,NaN,8:00 AM,2:00 PM,Kolkata
101,Dr. Janaki Raman,General+Physician,48.0,"PG Dip Diet, B.Sc. - Dietitic",₹ 0,₹ 0,NaN,NaN,12:00 PM,6:00 PM,Kolkata
102,Dr. Abhijit Ray,General+Physician,13.0,M.Sc - Dietitic,₹ 700,₹ 300,Diet Home Clinic,Barrackpore,11:00 AM,2:00 PM,Kolkata
103,Dr. Ayan Mukherjee,General+Physician,17.0,"B.Sc- Food & Nutrition, M.Sc- Food Science & N...",₹ 500,₹ 250,Doctors & Doctors,Sector V,11:00 AM,6:30 PM,Kolkata
104,Dr. Chandan Malik,General+Physician,25.0,"Masters in Nutritional Therapy, Diabetes Educa...",₹ 0,₹ 0,NaN,NaN,10:00 AM,6:00 PM,Kolkata
105,Dr. Debabrata Sarkar,General+Physician,8.0,Diploma in Obesity Management & Clinical Medic...,₹ 0,₹ 0,NaN,NaN,4:00 PM,6:00 PM,Kolkata
106,Dr. Jayita Chattopadhyay,General+Physician,13.0,"Diploma in Dietetics Health & Nutrition, Post ...",₹ 500,₹ 350,Nutrizone Diet Clinic,New Alipore,10:00 AM,7:00 PM,Kolkata
107,Abhishek Chakrabarti,General+Physician,10.0,M.Sc - Dietitic,₹ 600,₹ 250,Bright healthcare and wellness pvt.ltd,Sakher Bazar,4:30 PM,8:00 PM,Kolkata
108,Dr. Mangala Roy,General+Physician,14.0,"M. SC. , B.Sc. - Dietitic",₹ 400,₹ 0,Peerless Hospital City Diagnostic Centre,Girish Park,6:00 PM,7:00 PM,Kolkata
109,S. P. Chowdhury,General+Physician,10.0,"Diploma in Nutrition & Dietetic, Child Care Nu...",₹ 500,₹ 300,Urvaraa IVF,Ballygunge,2:00 PM,5:00 PM,Kolkata
110,Dr. Subha Metya,General+Physician,10.0,"M.Sc .CDE, Certificate course in Programming ...",₹ 400,₹ 400,Nutri Mania,Kasba,7:00 AM,8:30 PM,Kolkata
111,Dr. Indranil Khan,General+Physician,5.0,Clinical Nutritionist,₹ 0,₹ 350,NutriHeal Clinic,Ho Chi Minh Sarani,10:00 AM,8:00 PM,Kolkata
112,Dr. Goma Bali Bajaj,General+Physician,12.0,"BSc, Diploma In Diet & Nutrition, Post Graduat...",₹ 0,₹ 350,The Homely Diet Clinic,Salt Lake,11:00 AM,2:00 PM,Kolkata
113,Dr. Dibyendu Dutta,General+Physician,34.0,"MSC in Food Processing and Nutrition, Diploma ...",₹ 800,₹ 350,Health Point Nursing Home,Paddapukur Road,10:00 AM,8:45 PM,Kolkata
114,Dr. Bhaswar Bhattacherjee,General+Physician,12.0,"DNHE, Diploma In Diet & Nutrition",₹ 0,₹ 350,JM Nutrition,Kolkata,11:00 AM,1:00 PM,Kolkata
115,Dr. Debasish Pal,General+Physician,17.0,"PhD in Clinical Nutrition, M Sc Food Science a...",₹ 0,₹ 0,NaN,NaN,12:30 PM,5:00 PM,Kolkata
116,Dr. Sukanta Das Md Dph Mbbs,General+Physician,7.0,"MSc - Food and Applied Nutrition, Certified sp...",₹ 0,₹ 0,NaN,NaN,11:00 AM,8:00 PM,Kolkata
117,Dr. Aakash Pal,General+Physician,9.0,"Diploma in Dietetics, Health and Nutrition (DDHN)",₹ 0,₹ 300,Dt. Seema Poddar Diet Clinic,Camac Street,11:00 AM,5:30 PM,Kolkata
118,Dr. Dipu Shaw,General+Physician,16.0,"RD (All India Topper), MSc. Clinical Nutrition...",₹ 600,₹ 0,N.G Medicare Clinic,Rash Behari Avenue,3:00 PM,6:00 PM,Kolkata
119,Dr. Jyoti Biswas,General+Physician,12.0,"Certificate in Food Nutrition, MSc - Dietitic",₹ 0,₹ 0,NaN,NaN,10:00 AM,2:00 PM,Kolkata

# filling education with (not mentioned)

In [33]:
df['Education'].fillna('Not Mentioned', inplace = True)

In [34]:
df[df['Education'] == 'Not Mentioned']

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Available From,Available Till,City
25,Dr. Neha Banerjee,Dentist,NaN,Not Mentioned,₹ 300,₹ 200,Smile,Kolkata,10:00 AM,9:00 PM,Kolkata
41,Deepshikha Chowdhury,Dentist,NaN,Not Mentioned,₹ 500,₹ 250,Dr. Deepshikha Chowdhury Multispeciality Denta...,Beliaghata,4:00 PM,7:00 PM,Kolkata
67,Dt. Seema Poddar,Dietitian/Nutritionist,NaN,Not Mentioned,₹ 0,₹ 0,NaN,NaN,7:00 AM,9:00 PM,Kolkata
70,Dt. Soumi Sinha,Dietitian/Nutritionist,NaN,Not Mentioned,₹ 250,₹ 0,Dr. Paul's Advanced Hair And Skin Solutions – ...,Kolkata,11:00 AM,7:15 PM,Kolkata
80,Dr. Madhurima Roy,Dietitian/Nutritionist,NaN,Not Mentioned,₹ 700,₹ 400,Medithics Clinic (On Call),Mukundapur,10:00 AM,2:30 PM,Kolkata
...,...,...,...,...,...,...,...,...,...,...,...
2888,Mbs Holistic Clinic,Psychologist,NaN,Not Mentioned,₹ 0,₹ 0,NaN,NaN,7:00 AM,8:00 PM,Bangalore
2891,Ms. Tamanna Chaudhary,Psychologist,NaN,Not Mentioned,₹ 0,₹ 0,NaN,NaN,10:00 AM,6:00 PM,Bangalore
2892,Mr. Mahesh Natarajan,Psychologist,NaN,Not Mentioned,₹ 0,₹ 0,NaN,NaN,NaN,NaN,Bangalore
2898,Ms. Seema Pradhan,Psychologist,NaN,Not Mentioned,₹ 0,₹ 0,NaN,NaN,2:00 PM,3:30 PM,Bangalore
2928,Ayur Jagruti Clinic,Ayurveda,NaN,Not Mentioned,₹ 300,₹ 300,Ayur Jagruti Ayurveda Clinic,Indira Nagar,2:00 PM,4:00 PM,Bangalore

In [35]:
df.isnull().sum()

Name                       0
Specialization             0
Experience (in years)    171
Education                  0
Fee at clinic              0
Online Fee                 0
Clinic Name              597
Area                     598
Available From           119
Available Till           119
City                       0
dtype: int64

## Filling Experience columns null values with (Not Mentioned)

In [36]:
df[df['Experience (in years)'].isnull()]

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Available From,Available Till,City
25,Dr. Neha Banerjee,Dentist,NaN,Not Mentioned,₹ 300,₹ 200,Smile,Kolkata,10:00 AM,9:00 PM,Kolkata
41,Deepshikha Chowdhury,Dentist,NaN,Not Mentioned,₹ 500,₹ 250,Dr. Deepshikha Chowdhury Multispeciality Denta...,Beliaghata,4:00 PM,7:00 PM,Kolkata
67,Dt. Seema Poddar,Dietitian/Nutritionist,NaN,Not Mentioned,₹ 0,₹ 0,NaN,NaN,7:00 AM,9:00 PM,Kolkata
70,Dt. Soumi Sinha,Dietitian/Nutritionist,NaN,Not Mentioned,₹ 250,₹ 0,Dr. Paul's Advanced Hair And Skin Solutions – ...,Kolkata,11:00 AM,7:15 PM,Kolkata
80,Dr. Madhurima Roy,Dietitian/Nutritionist,NaN,Not Mentioned,₹ 700,₹ 400,Medithics Clinic (On Call),Mukundapur,10:00 AM,2:30 PM,Kolkata
...,...,...,...,...,...,...,...,...,...,...,...
2888,Mbs Holistic Clinic,Psychologist,NaN,Not Mentioned,₹ 0,₹ 0,NaN,NaN,7:00 AM,8:00 PM,Bangalore
2891,Ms. Tamanna Chaudhary,Psychologist,NaN,Not Mentioned,₹ 0,₹ 0,NaN,NaN,10:00 AM,6:00 PM,Bangalore
2892,Mr. Mahesh Natarajan,Psychologist,NaN,Not Mentioned,₹ 0,₹ 0,NaN,NaN,NaN,NaN,Bangalore
2898,Ms. Seema Pradhan,Psychologist,NaN,Not Mentioned,₹ 0,₹ 0,NaN,NaN,2:00 PM,3:30 PM,Bangalore
2928,Ayur Jagruti Clinic,Ayurveda,NaN,Not Mentioned,₹ 300,₹ 300,Ayur Jagruti Ayurveda Clinic,Indira Nagar,2:00 PM,4:00 PM,Bangalore

In [37]:
df['Experience (in years)'].fillna('Not Mentioned', inplace = True)

In [38]:
df.isnull().sum()

Name                       0
Specialization             0
Experience (in years)      0
Education                  0
Fee at clinic              0
Online Fee                 0
Clinic Name              597
Area                     598
Available From           119
Available Till           119
City                       0
dtype: int64

# removing rows with more than  2 nan values

In [39]:
df.dropna(thresh = 8, axis = 0,inplace = True)

In [40]:
df.isnull().sum()

Name                       0
Specialization             0
Experience (in years)      0
Education                  0
Fee at clinic              0
Online Fee                 0
Clinic Name              549
Area                     550
Available From            71
Available Till            71
City                       0
dtype: int64

# Removing null Clinic Name & Area Name

In [41]:
df.columns

Index(['Name', 'Specialization', 'Experience (in years)', 'Education',
       'Fee at clinic', 'Online Fee', 'Clinic Name', 'Area', 'Available From',
       'Available Till', 'City'],
      dtype='object')

In [42]:
df = df[~((df['Clinic Name'].isnull())|(df['Area'].isnull()))]

In [43]:
df.reset_index(drop = True,inplace = True)

In [44]:
df

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Available From,Available Till,City
0,Dr. Kaustubh Das,Dentist,22.0,"BDS, MFDS RCPS(Glasgow), FFD RCS (IRE)",₹ 500,₹ 0,ASPIRE CLINIC,Kolkata,10:00 AM,7:00 PM,Kolkata
1,Dr. Asif Naushad,Dentist,19.0,"House Surgeon, House Surgeon, House Surgeon, BDS",₹ 300,₹ 300,JM DENTAL,Kolkata,10:00 AM,9:00 PM,Kolkata
2,Dr. Prabhjeet Singh Sethi,Dentist,24.0,Certified Implantologist,₹ 500,₹ 350,Dontia Dental Care,Kolkata,3:00 PM,8:00 PM,Kolkata
3,Dr. Dibyendu Dutta,Dentist,30.0,"Certified Implantologist, Advanced Aesthetics,...",₹ 300,₹ 500,Smilz Dental Treatment Facility,www.smilz.net,11:00 AM,1:00 PM,Kolkata
4,Dr. Sanket Chakraverty,Dentist,15.0,"MDS Prosthodontics, B.D.S",₹ 300,₹ 300,Teeth Care Multispeciality Dental Clinic,Rajarhat Road,4:30 PM,8:30 PM,Kolkata
...,...,...,...,...,...,...,...,...,...,...,...
2300,Dr. Niveditha Shree K N,Ayurveda,12.0,Bachelor of Ayurvedic Medicine & Surgery,₹ 200,₹ 100,Ashwini Ayurveda,Banashankari,6:30 PM,10:00 PM,Bangalore
2301,Dr. Arjun S Jogdankar,Ayurveda,10.0,"Bachelor of Ayurveda, Medicine and Surgery (BAMS)",₹ 500,₹ 500,NIROGSTREET 1VEDA MULTISPECIALITY AYURVEDA AND...,Bang,10:00 AM,7:30 AM,Bangalore
2302,Dr. Sumedha K A,Ayurveda,11.0,"BAMS, M.D Panchakarma",₹ 300,₹ 200,Shathayu Ayurveda clinic,AECS Layout,9:00 AM,7:30 PM,Bangalore
2303,Dr. Prema Jyothi Fraser,Ayurveda,8.0,MD,₹ 200,₹ 200,Sri Mahima Multispecality Homoeo Clinic,Jayanagar,5:00 PM,8:30 PM,Bangalore
2304,Dr. Kavya Kadapi Kossambe,Ayurveda,6.0,MD - Ayurveda,₹ 300,₹ 300,Kaya chikitsalaya,ISRO Layout,10:00 AM,1:00 PM,Bangalore

In [45]:
import re
area = []
for i in df['Area'] :
    if re.findall(r'^\d+',i) :
        area.append(np.nan)
    elif re.findall(r'^www.',i) or i == 'S':
        area.append(np.nan)
    elif i == 'Bang' :
        area.append('Bangalore')
    else :
        area.append(i)

In [46]:
df['Area'] = area

C:\Users\DELL\AppData\Local\Temp\ipykernel_11320\2950117602.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Area'] = area

In [47]:
df.isnull().sum()

Name                      0
Specialization            0
Experience (in years)     0
Education                 0
Fee at clinic             0
Online Fee                0
Clinic Name               0
Area                     69
Available From           71
Available Till           71
City                      0
dtype: int64

# removing unstable data rows

In [48]:
df = df[~df['Area'].isnull()]

In [49]:
df[df['Available From'].isnull()]

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Available From,Available Till,City
30,Dr. Soumendu Bhattacharya,Dentist,18.0,BDS,₹ 300,₹ 300,ANGEL DENTAL CLINIC,Ambagan,NaN,NaN,Kolkata
97,Dr. S M Ali,General+Physician,13.0,M.Sc - Dietitic,₹ 0,₹ 150,Bright Healthcare & Wellness Private Limited,Behala Chowrasta,NaN,NaN,Kolkata
102,Biswadeep Sengupta,General+Physician,11.0,"M.Sc in Applied Nutrition, B.Sc. - Dietitic",₹ 0,₹ 850,Health help - With Sneha Majumder,Haltu,NaN,NaN,Kolkata
107,Dr. Debashis Chatterjee,General+Physician,13.0,"Masters in Nutritional Therapy, N.E.T, IDA Cou...",₹ 0,₹ 300,Millennium Health Care,Salt Lake,NaN,NaN,Kolkata
111,Dr. Asok Kumar Nandi,General+Physician,12.0,M.sc in dietetics and community nutrittion man...,₹ 500,₹ 300,Dr.B.C.Roy Hospital,Kolkata,NaN,NaN,Kolkata
...,...,...,...,...,...,...,...,...,...,...,...
2104,Dr. Shafi Shali,General+Physician,24.0,Fellow of Academy of General Education (FAGE),₹ 0,₹ 150,Yet to Start,Bangalore,NaN,NaN,Bangalore
2220,Dr. Merlin Patrao,Homeopathy,16.0,"BHMS, PGDCR",₹ 0,₹ 300,Dr Merlin Patrao,Malleshwaram,NaN,NaN,Bangalore
2241,Dr. Sravani P,Homeopathy,13.0,MD (Hom),₹ 0,₹ 300,Bharadwaj Homoeo Clinic,Gagan Vihar,NaN,NaN,Bangalore
2263,Ms. Geetha.G. Rao,Psychologist,15.0,M.Sc - Clinical Psychology,₹ 0,₹ 250,Geetha. Rao,Bangalore,NaN,NaN,Bangalore
2268,Mr. Gangaram Prem Kumar,Psychologist,11.0,Diploma in Counselling,₹ 0,₹ 500,TSMS,Bangalore,NaN,NaN,Bangalore

In [50]:
df[(df['Available From'].isnull()) & (df['Available Till'].isnull())]

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Available From,Available Till,City
30,Dr. Soumendu Bhattacharya,Dentist,18.0,BDS,₹ 300,₹ 300,ANGEL DENTAL CLINIC,Ambagan,NaN,NaN,Kolkata
97,Dr. S M Ali,General+Physician,13.0,M.Sc - Dietitic,₹ 0,₹ 150,Bright Healthcare & Wellness Private Limited,Behala Chowrasta,NaN,NaN,Kolkata
102,Biswadeep Sengupta,General+Physician,11.0,"M.Sc in Applied Nutrition, B.Sc. - Dietitic",₹ 0,₹ 850,Health help - With Sneha Majumder,Haltu,NaN,NaN,Kolkata
107,Dr. Debashis Chatterjee,General+Physician,13.0,"Masters in Nutritional Therapy, N.E.T, IDA Cou...",₹ 0,₹ 300,Millennium Health Care,Salt Lake,NaN,NaN,Kolkata
111,Dr. Asok Kumar Nandi,General+Physician,12.0,M.sc in dietetics and community nutrittion man...,₹ 500,₹ 300,Dr.B.C.Roy Hospital,Kolkata,NaN,NaN,Kolkata
...,...,...,...,...,...,...,...,...,...,...,...
2104,Dr. Shafi Shali,General+Physician,24.0,Fellow of Academy of General Education (FAGE),₹ 0,₹ 150,Yet to Start,Bangalore,NaN,NaN,Bangalore
2220,Dr. Merlin Patrao,Homeopathy,16.0,"BHMS, PGDCR",₹ 0,₹ 300,Dr Merlin Patrao,Malleshwaram,NaN,NaN,Bangalore
2241,Dr. Sravani P,Homeopathy,13.0,MD (Hom),₹ 0,₹ 300,Bharadwaj Homoeo Clinic,Gagan Vihar,NaN,NaN,Bangalore
2263,Ms. Geetha.G. Rao,Psychologist,15.0,M.Sc - Clinical Psychology,₹ 0,₹ 250,Geetha. Rao,Bangalore,NaN,NaN,Bangalore
2268,Mr. Gangaram Prem Kumar,Psychologist,11.0,Diploma in Counselling,₹ 0,₹ 500,TSMS,Bangalore,NaN,NaN,Bangalore

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2236 entries, 0 to 2304
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Name                   2236 non-null   object
 1   Specialization         2236 non-null   object
 2   Experience (in years)  2236 non-null   object
 3   Education              2236 non-null   object
 4   Fee at clinic          2236 non-null   object
 5   Online Fee             2236 non-null   object
 6   Clinic Name            2236 non-null   object
 7   Area                   2236 non-null   object
 8   Available From         2166 non-null   object
 9   Available Till         2166 non-null   object
 10  City                   2236 non-null   object
dtypes: object(11)
memory usage: 209.6+ KB

# Data type conversion

### converting Experience from object to numeric 
- Keeping all the Not Mentioned values in experience columns as `zero` so the columns can be converted to numeric type

In [52]:
df['Experience (in years)'] = df['Experience (in years)'].apply(lambda x : 0 if x == 'Not Mentioned' else x)

C:\Users\DELL\AppData\Local\Temp\ipykernel_11320\4065950866.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Experience (in years)'] = df['Experience (in years)'].apply(lambda x : 0 if x == 'Not Mentioned' else x)

### Removing unstable data rows based on Fee at clinic columns

In [53]:
df[df['Fee at clinic'] == '₹ 56']

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Available From,Available Till,City
1294,Mr. Shashi Rayka,Dietitian/Nutritionist,0.0,Not Mentioned,₹ 56,₹ 0,12,Fortis Malar Hospital,10:00 AM,8:15 PM,Chennai

In [54]:
df = df.reset_index(drop = True)

In [55]:
df = df.reset_index(drop = True)

In [95]:
df[df['Fee at clinic'] == '₹ 45']

Empty DataFrame
Columns: [Name, Specialization, Experience (in years), Education, Fee at clinic, Online Fee, Clinic Name, Area, Available From, Available Till, City, Total Fee, Number of Hrs. Available]
Index: []

In [96]:
df.iloc[[1247],:]

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Available From,Available Till,City,Total Fee,Number of Hrs. Available
1248,Dt. Ms. Shiny Esther,Dietitian/Nutritionist,12.0,"M.sc - Foods and Nutrition, B.Sc - Food Servic...",0.0,0.0,Qua Nutrition Anna nagar,Anna Nagar East,10:00:00,19:00:00,Chennai,0.0,09:00

In [ ]:
df.drop(1247,axis = 0,inplace = True)

In [110]:
df[df['Fee at clinic'] == '₹ 56']

Empty DataFrame
Columns: [Name, Specialization, Experience (in years), Education, Fee at clinic, Online Fee, Clinic Name, Area, Available From, Available Till, City, Total Fee, Number of Hrs. Available]
Index: []

In [111]:
df.iloc[[1244]]

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Available From,Available Till,City,Total Fee,Number of Hrs. Available
1244,Mr. Shashi Rayka,Dietitian/Nutritionist,0.0,Not Mentioned,56.0,0.0,12,Fortis Malar Hospital,10:00:00,20:15:00,Chennai,56.0,10:15

In [112]:
df.drop(1244, axis = 0, inplace = True)

In [106]:
df.iloc[[1244]]

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Available From,Available Till,City,Total Fee,Number of Hrs. Available
1244,Mr. Shashi Rayka,Dietitian/Nutritionist,0.0,Not Mentioned,56.0,0.0,12,Fortis Malar Hospital,10:00:00,20:15:00,Chennai,56.0,10:15

In [99]:
df.iloc[[1243]]

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Available From,Available Till,City,Total Fee,Number of Hrs. Available
1244,Dt. Geetha Veeraraju,Dietitian/Nutritionist,0.0,Not Mentioned,500.0,0.0,Wonder Diet Clinic,Medavakkam,07:00:00,23:00:00,Chennai,500.0,16:00

In [100]:
df.drop(1243, axis = 0, inplace = True)

KeyError: '[1243] not found in axis'

In [88]:
df.iloc[[1243]]

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Available From,Available Till,City,Total Fee,Number of Hrs. Available
1244,Dt. Geetha Veeraraju,Dietitian/Nutritionist,0.0,Not Mentioned,500.0,0.0,Wonder Diet Clinic,Medavakkam,07:00:00,23:00:00,Chennai,500.0,16:00

In [58]:
df.iloc[[1242]]

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Available From,Available Till,City
1242,Mr. Rakesh K,Dietitian/Nutritionist,0.0,Not Mentioned,₹ 44,₹ 0,fgggg,Rajakulam,9:00 AM,11:45 AM,Chennai

In [101]:
df.drop(1242, axis = 0, inplace = True)

In [102]:
df.iloc[[1242]]

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Available From,Available Till,City,Total Fee,Number of Hrs. Available
1244,Dt. Geetha Veeraraju,Dietitian/Nutritionist,0.0,Not Mentioned,500.0,0.0,Wonder Diet Clinic,Medavakkam,07:00:00,23:00:00,Chennai,500.0,16:00

In [113]:
df

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Available From,Available Till,City,Total Fee,Number of Hrs. Available
0,Dr. Kaustubh Das,Dentist,22.0,"BDS, MFDS RCPS(Glasgow), FFD RCS (IRE)",500.0,0.0,ASPIRE CLINIC,Kolkata,10:00:00,19:00:00,Kolkata,500.0,09:00
1,Dr. Asif Naushad,Dentist,19.0,"House Surgeon, House Surgeon, House Surgeon, BDS",300.0,300.0,JM DENTAL,Kolkata,10:00:00,21:00:00,Kolkata,600.0,11:00
2,Dr. Prabhjeet Singh Sethi,Dentist,24.0,Certified Implantologist,500.0,350.0,Dontia Dental Care,Kolkata,15:00:00,20:00:00,Kolkata,850.0,05:00
3,Dr. Sanket Chakraverty,Dentist,15.0,"MDS Prosthodontics, B.D.S",300.0,300.0,Teeth Care Multispeciality Dental Clinic,Rajarhat Road,16:30:00,20:30:00,Kolkata,600.0,04:00
4,Dr. Subhajit Dutta,Dentist,13.0,BDS,500.0,300.0,SIGNATURE SMILE Dental Clinic,Kolkata,17:00:00,21:00:00,Kolkata,800.0,04:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2228,Dr. Niveditha Shree K N,Ayurveda,12.0,Bachelor of Ayurvedic Medicine & Surgery,200.0,100.0,Ashwini Ayurveda,Banashankari,18:30:00,22:00:00,Bangalore,300.0,03:30
2229,Dr. Arjun S Jogdankar,Ayurveda,10.0,"Bachelor of Ayurveda, Medicine and Surgery (BAMS)",500.0,500.0,NIROGSTREET 1VEDA MULTISPECIALITY AYURVEDA AND...,Bangalore,10:00:00,07:30:00,Bangalore,1000.0,21:30
2230,Dr. Sumedha K A,Ayurveda,11.0,"BAMS, M.D Panchakarma",300.0,200.0,Shathayu Ayurveda clinic,AECS Layout,09:00:00,19:30:00,Bangalore,500.0,10:30
2231,Dr. Prema Jyothi Fraser,Ayurveda,8.0,MD,200.0,200.0,Sri Mahima Multispecality Homoeo Clinic,Jayanagar,17:00:00,20:30:00,Bangalore,400.0,03:30
2232,Dr. Kavya Kadapi Kossambe,Ayurveda,6.0,MD - Ayurveda,300.0,300.0,Kaya chikitsalaya,ISRO Layout,10:00:00,13:00:00,Bangalore,600.0,03:00

In [104]:
df.reset_index(drop = True, inplace = True)

In [119]:
df

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Available From,Available Till,City,Total Fee,Number of Hrs. Available
0,Dr. Kaustubh Das,Dentist,22.0,"BDS, MFDS RCPS(Glasgow), FFD RCS (IRE)",500.0,0.0,ASPIRE CLINIC,Kolkata,10:00:00,19:00:00,Kolkata,500.0,09:00
1,Dr. Asif Naushad,Dentist,19.0,"House Surgeon, House Surgeon, House Surgeon, BDS",300.0,300.0,JM DENTAL,Kolkata,10:00:00,21:00:00,Kolkata,600.0,11:00
2,Dr. Prabhjeet Singh Sethi,Dentist,24.0,Certified Implantologist,500.0,350.0,Dontia Dental Care,Kolkata,15:00:00,20:00:00,Kolkata,850.0,05:00
3,Dr. Sanket Chakraverty,Dentist,15.0,"MDS Prosthodontics, B.D.S",300.0,300.0,Teeth Care Multispeciality Dental Clinic,Rajarhat Road,16:30:00,20:30:00,Kolkata,600.0,04:00
4,Dr. Subhajit Dutta,Dentist,13.0,BDS,500.0,300.0,SIGNATURE SMILE Dental Clinic,Kolkata,17:00:00,21:00:00,Kolkata,800.0,04:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2228,Dr. Niveditha Shree K N,Ayurveda,12.0,Bachelor of Ayurvedic Medicine & Surgery,200.0,100.0,Ashwini Ayurveda,Banashankari,18:30:00,22:00:00,Bangalore,300.0,03:30
2229,Dr. Arjun S Jogdankar,Ayurveda,10.0,"Bachelor of Ayurveda, Medicine and Surgery (BAMS)",500.0,500.0,NIROGSTREET 1VEDA MULTISPECIALITY AYURVEDA AND...,Bangalore,10:00:00,07:30:00,Bangalore,1000.0,21:30
2230,Dr. Sumedha K A,Ayurveda,11.0,"BAMS, M.D Panchakarma",300.0,200.0,Shathayu Ayurveda clinic,AECS Layout,09:00:00,19:30:00,Bangalore,500.0,10:30
2231,Dr. Prema Jyothi Fraser,Ayurveda,8.0,MD,200.0,200.0,Sri Mahima Multispecality Homoeo Clinic,Jayanagar,17:00:00,20:30:00,Bangalore,400.0,03:30
2232,Dr. Kavya Kadapi Kossambe,Ayurveda,6.0,MD - Ayurveda,300.0,300.0,Kaya chikitsalaya,ISRO Layout,10:00:00,13:00:00,Bangalore,600.0,03:00

### Conversion of `Fee at clinic` column from object to numeric

- Removing `₹ ` from the columns so the column can be converted to numerical type
- Converting datatype of the column using astype() method

In [64]:
df['Fee at clinic'] = df['Fee at clinic'].apply(lambda x : x.split(' ')[1])

In [65]:
df['Fee at clinic'] = df['Fee at clinic'].astype('float')

### Conversion of `Online Fee` column from object to numeric

- Removing `₹ ` from the columns so the column can be converted to numerical type
- Converting datatype of the column using astype() method

In [66]:
df['Online Fee'] = df['Online Fee'].apply(lambda x : x.split(' ')[1])

In [67]:
df['Online Fee'] = df['Online Fee'].astype('float')

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2235 entries, 0 to 2234
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Name                   2235 non-null   object
 1   Specialization         2235 non-null   object
 2   Experience (in years)  2235 non-null   float64
 3   Education              2235 non-null   object
 4   Fee at clinic          2235 non-null   float64
 5   Online Fee             2235 non-null   float64
 6   Clinic Name            2235 non-null   object
 7   Area                   2235 non-null   object
 8   Available From         2165 non-null   object
 9   Available Till         2165 non-null   object
 10  City                   2235 non-null   object
dtypes: float64(3), object(8)
memory usage: 192.2+ KB

# Adding new column Total Fee 
- using sum of `Online Fee` and `Fee at clinic` columns

In [114]:
df['Total Fee'] = df['Online Fee'] + df['Fee at clinic']

In [115]:
len(df[df['Total Fee'] == 0])

12

# converting Timing columns to datetime object 
> steps :
1. Converting `Available From` and `Available Till` columns to datetime format.
2. Creating new column `Number of Hrs. Available` to show total number of hours of availability by subtracting time delta of `Available Till`  from time delta of `Available From`
3. Removing days part from the `Number of Hrs. Available` column

In [116]:
df.columns

Index(['Name', 'Specialization', 'Experience (in years)', 'Education',
       'Fee at clinic', 'Online Fee', 'Clinic Name', 'Area', 'Available From',
       'Available Till', 'City', 'Total Fee', 'Number of Hrs. Available'],
      dtype='object')

In [117]:
# Convert the time column to datetime data type
df['Available From'] = pd.to_datetime(df['Available From'], format='%I:%M %p').dt.time
df['Available Till'] = pd.to_datetime(df['Available Till'], format='%I:%M %p').dt.time

ValueError: time data "10:00:00" doesn't match format "%I:%M %p", at position 0. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [118]:
df.head()

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Available From,Available Till,City,Total Fee,Number of Hrs. Available
0,Dr. Kaustubh Das,Dentist,22.0,"BDS, MFDS RCPS(Glasgow), FFD RCS (IRE)",500.0,0.0,ASPIRE CLINIC,Kolkata,10:00:00,19:00:00,Kolkata,500.0,09:00
1,Dr. Asif Naushad,Dentist,19.0,"House Surgeon, House Surgeon, House Surgeon, BDS",300.0,300.0,JM DENTAL,Kolkata,10:00:00,21:00:00,Kolkata,600.0,11:00
2,Dr. Prabhjeet Singh Sethi,Dentist,24.0,Certified Implantologist,500.0,350.0,Dontia Dental Care,Kolkata,15:00:00,20:00:00,Kolkata,850.0,05:00
3,Dr. Sanket Chakraverty,Dentist,15.0,"MDS Prosthodontics, B.D.S",300.0,300.0,Teeth Care Multispeciality Dental Clinic,Rajarhat Road,16:30:00,20:30:00,Kolkata,600.0,04:00
4,Dr. Subhajit Dutta,Dentist,13.0,BDS,500.0,300.0,SIGNATURE SMILE Dental Clinic,Kolkata,17:00:00,21:00:00,Kolkata,800.0,04:00

In [74]:
df['Number of Hrs. Available'] = (pd.to_timedelta(df['Available Till'].astype(str)) - pd.to_timedelta(df['Available From'].astype(str)))

In [75]:
df

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Available From,Available Till,City,Total Fee,Number of Hrs. Available
0,Dr. Kaustubh Das,Dentist,22.0,"BDS, MFDS RCPS(Glasgow), FFD RCS (IRE)",500.0,0.0,ASPIRE CLINIC,Kolkata,10:00:00,19:00:00,Kolkata,500.0,0 days 09:00:00
1,Dr. Asif Naushad,Dentist,19.0,"House Surgeon, House Surgeon, House Surgeon, BDS",300.0,300.0,JM DENTAL,Kolkata,10:00:00,21:00:00,Kolkata,600.0,0 days 11:00:00
2,Dr. Prabhjeet Singh Sethi,Dentist,24.0,Certified Implantologist,500.0,350.0,Dontia Dental Care,Kolkata,15:00:00,20:00:00,Kolkata,850.0,0 days 05:00:00
3,Dr. Sanket Chakraverty,Dentist,15.0,"MDS Prosthodontics, B.D.S",300.0,300.0,Teeth Care Multispeciality Dental Clinic,Rajarhat Road,16:30:00,20:30:00,Kolkata,600.0,0 days 04:00:00
4,Dr. Subhajit Dutta,Dentist,13.0,BDS,500.0,300.0,SIGNATURE SMILE Dental Clinic,Kolkata,17:00:00,21:00:00,Kolkata,800.0,0 days 04:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2230,Dr. Niveditha Shree K N,Ayurveda,12.0,Bachelor of Ayurvedic Medicine & Surgery,200.0,100.0,Ashwini Ayurveda,Banashankari,18:30:00,22:00:00,Bangalore,300.0,0 days 03:30:00
2231,Dr. Arjun S Jogdankar,Ayurveda,10.0,"Bachelor of Ayurveda, Medicine and Surgery (BAMS)",500.0,500.0,NIROGSTREET 1VEDA MULTISPECIALITY AYURVEDA AND...,Bangalore,10:00:00,07:30:00,Bangalore,1000.0,-1 days +21:30:00
2232,Dr. Sumedha K A,Ayurveda,11.0,"BAMS, M.D Panchakarma",300.0,200.0,Shathayu Ayurveda clinic,AECS Layout,09:00:00,19:30:00,Bangalore,500.0,0 days 10:30:00
2233,Dr. Prema Jyothi Fraser,Ayurveda,8.0,MD,200.0,200.0,Sri Mahima Multispecality Homoeo Clinic,Jayanagar,17:00:00,20:30:00,Bangalore,400.0,0 days 03:30:00
2234,Dr. Kavya Kadapi Kossambe,Ayurveda,6.0,MD - Ayurveda,300.0,300.0,Kaya chikitsalaya,ISRO Layout,10:00:00,13:00:00,Bangalore,600.0,0 days 03:00:00

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2235 entries, 0 to 2234
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Name                      2235 non-null   object
 1   Specialization            2235 non-null   object
 2   Experience (in years)     2235 non-null   float64
 3   Education                 2235 non-null   object
 4   Fee at clinic             2235 non-null   float64
 5   Online Fee                2235 non-null   float64
 6   Clinic Name               2235 non-null   object
 7   Area                      2235 non-null   object
 8   Available From            2165 non-null   object
 9   Available Till            2165 non-null   object
 10  City                      2235 non-null   object
 11  Total Fee                 2235 non-null   float64
 12  Number of Hrs. Available  2165 non-null   timedelta64[ns]
dtypes: float64(4), object(8), timedelta64[ns](1)
memory usage: 227.1+ KB

In [77]:
hrs = []
for i in df['Number of Hrs. Available'] :
    b = re.findall(r'days (.+):00$',str(i))
    if len(b) > 0 :
        if b[0][0] == '+' :
            hrs.append(b[0][1:])
        else :
            hrs.append(b[0])
    else :
        hrs.append(i)

In [78]:
df['Number of Hrs. Available'] = hrs

In [79]:
df.rename({'Number of Hrs. Available' : 'Number of Hrs. Available (HH:MM)'},inplace = True)

In [80]:
df

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Available From,Available Till,City,Total Fee,Number of Hrs. Available
0,Dr. Kaustubh Das,Dentist,22.0,"BDS, MFDS RCPS(Glasgow), FFD RCS (IRE)",500.0,0.0,ASPIRE CLINIC,Kolkata,10:00:00,19:00:00,Kolkata,500.0,09:00
1,Dr. Asif Naushad,Dentist,19.0,"House Surgeon, House Surgeon, House Surgeon, BDS",300.0,300.0,JM DENTAL,Kolkata,10:00:00,21:00:00,Kolkata,600.0,11:00
2,Dr. Prabhjeet Singh Sethi,Dentist,24.0,Certified Implantologist,500.0,350.0,Dontia Dental Care,Kolkata,15:00:00,20:00:00,Kolkata,850.0,05:00
3,Dr. Sanket Chakraverty,Dentist,15.0,"MDS Prosthodontics, B.D.S",300.0,300.0,Teeth Care Multispeciality Dental Clinic,Rajarhat Road,16:30:00,20:30:00,Kolkata,600.0,04:00
4,Dr. Subhajit Dutta,Dentist,13.0,BDS,500.0,300.0,SIGNATURE SMILE Dental Clinic,Kolkata,17:00:00,21:00:00,Kolkata,800.0,04:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2230,Dr. Niveditha Shree K N,Ayurveda,12.0,Bachelor of Ayurvedic Medicine & Surgery,200.0,100.0,Ashwini Ayurveda,Banashankari,18:30:00,22:00:00,Bangalore,300.0,03:30
2231,Dr. Arjun S Jogdankar,Ayurveda,10.0,"Bachelor of Ayurveda, Medicine and Surgery (BAMS)",500.0,500.0,NIROGSTREET 1VEDA MULTISPECIALITY AYURVEDA AND...,Bangalore,10:00:00,07:30:00,Bangalore,1000.0,21:30
2232,Dr. Sumedha K A,Ayurveda,11.0,"BAMS, M.D Panchakarma",300.0,200.0,Shathayu Ayurveda clinic,AECS Layout,09:00:00,19:30:00,Bangalore,500.0,10:30
2233,Dr. Prema Jyothi Fraser,Ayurveda,8.0,MD,200.0,200.0,Sri Mahima Multispecality Homoeo Clinic,Jayanagar,17:00:00,20:30:00,Bangalore,400.0,03:30
2234,Dr. Kavya Kadapi Kossambe,Ayurveda,6.0,MD - Ayurveda,300.0,300.0,Kaya chikitsalaya,ISRO Layout,10:00:00,13:00:00,Bangalore,600.0,03:00

In [120]:
df[(df['Specialization'] == 'Dentist') & (df['City'] == 'Hyderabad')]

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Available From,Available Till,City,Total Fee,Number of Hrs. Available
1501,Dr. Tejas Melkote,Dentist,20.0,"BDS, MDS - Pediatric Dentistry , Certificate C...",500.0,250.0,Tooth Fairy Dental Care,Kondapur,10:00:00,20:00:00,Hyderabad,750.0,10:00
1502,Dr. Afroz Ghori,Dentist,16.0,"MDS, BDS",100.0,0.0,Neelofar Dental,Madhapur,10:00:00,13:00:00,Hyderabad,100.0,03:00
1503,Dr. P Parameswar Naishadham,Dentist,15.0,"MDS (ORAL & MAXILLOFACIAL PATHOLOGY), BDS",200.0,200.0,Shree Jayalakshmi dental clinic,Badangpet,10:00:00,13:30:00,Hyderabad,400.0,03:30
1504,Dr. K R Maheshwar Reddy,Dentist,18.0,"MDS - Pediatric and Preventive Dentistry, BDS",200.0,200.0,Rushi Dental Care,Nallagandla,16:00:00,20:00:00,Hyderabad,400.0,04:00
1505,Dr. Y S Reddy,Dentist,27.0,BDS,300.0,100.0,YSR Speciality dental clinic,Ameerpet,17:30:00,20:30:00,Hyderabad,400.0,03:00
1506,Dr. Siddharth Bhalerao,Dentist,21.0,"BDS, MDS, MBA (Healthcare), FAM",200.0,0.0,Dental And Maxillo-facial Clinic Dental And Ma...,Banjara Hills,12:30:00,20:00:00,Hyderabad,200.0,07:30
1507,Dr. N.Vinod Gandhi,Dentist,12.0,"BDS, BDS",500.0,100.0,Dr.CARE DENTAL HOSPITAL,Hyderabad,10:00:00,19:00:00,Hyderabad,600.0,09:00
1508,Dr. Vineet Dubey,Dentist,14.0,BDS,100.0,100.0,Aarogyasree Army Dental Clinic,Secunderabad,NaT,NaT,Hyderabad,200.0,NaT
1509,Dr. Rishabh S Gupta,Dentist,13.0,"BDS, M.Sc - Master of Oral Implantology (MOI)",400.0,100.0,Tooth Tales Dental Hospital,Gachibowli,12:00:00,17:00:00,Hyderabad,500.0,05:00
1510,Dr. Sameer. G,Dentist,16.0,BDS,100.0,300.0,Dr. Sameer's Dental Clinic & Implant Centre,Hyderabad,10:00:00,21:00:00,Hyderabad,400.0,11:00
1511,Dr. Prasad Meka,Dentist,28.0,"MDS Prosthodontics, BDS",350.0,200.0,KIMS Dental Care,Secunderabad,09:00:00,17:30:00,Hyderabad,550.0,08:30
1512,Dr. Prathyusha Prasad,Dentist,28.0,"MDS, BDS",350.0,200.0,KIMS Dental Care,Secunderabad,09:00:00,17:30:00,Hyderabad,550.0,08:30
1513,Dr. Rajavardhan K,Dentist,12.0,MDS,200.0,100.0,SRAVANI DENTAL CARE,A.S Rao Nagar,10:00:00,20:30:00,Hyderabad,300.0,10:30
1514,Dr. Hormuzd K,Dentist,23.0,MDS - Periodontics,200.0,50.0,Dr Hormuzd K Vakil,Secunderabad,07:00:00,15:00:00,Hyderabad,250.0,08:00
1515,Dr. V.S Sharavana Kumar,Dentist,21.0,"MDS - Oral & Maxillofacial Surgery, BDS",200.0,150.0,Sundari Maternity And General Hospital,Alwal,10:00:00,13:00:00,Hyderabad,350.0,03:00
1516,Dr. Pogaku Rajkumar,Dentist,17.0,BDS,200.0,400.0,Dental City Super Speciality Dental Hospital,East Marredpally,09:30:00,13:30:00,Hyderabad,600.0,04:00
1517,Dr. Chaitanya Byragoni,Dentist,13.0,MDS Endodontist,100.0,0.0,OROCARE DENTAL CLINIC,Secunderabad,NaT,NaT,Hyderabad,100.0,NaT
1518,Dr. Firas Furruq Jahangir,Dentist,12.0,BDS,100.0,200.0,ToothWise Dental Hospital,Hyderabad,16:00:00,18:00:00,Hyderabad,300.0,02:00
1519,Dr. Mohammed Zakiullah,Dentist,11.0,BDS,100.0,100.0,Whitedent Dental Care,Gudimalkapur,17:00:00,22:00:00,Hyderabad,200.0,05:00
1520,Dr. Bharath Kommu,Dentist,14.0,BDS,200.0,0.0,SRI DURGA DENTAL CARE-HASTHINAPURAM SOUTH,Hastinapuram,09:00:00,19:00:00,Hyderabad,200.0,10:00
1521,Dr. K.Saigeeta,Dentist,10.0,"BDS, MDS - Pediatric Dentistry",100.0,200.0,Vijaya Dental Clinic,Secunderabad,17:00:00,21:00:00,Hyderabad,300.0,04:00
1522,Dr. Sampath Reddy,Dentist,27.0,"MDS ,Pediatric Dentistry",500.0,200.0,Little Smile Dental Hospital,Masab Tank,10:00:00,13:00:00,Hyderabad,700.0,03:00
1523,Dr. M. Vijaya Lakshmi,Dentist,26.0,"M.D.S, Post-Graduate Certificate in Oral Impla...",500.0,200.0,Lakshmi Dental Clinic,Hyderabad,10:00:00,13:00:00,Hyderabad,700.0,03:00
1524,Dr. Jhansi Lakshmi Kandregula,Dentist,14.0,"BDS, MDS - Periodontics",500.0,100.0,clove dental clinic,Hyderabad,09:00:00,19:00:00,Hyderabad,600.0,10:00
1525,Dr. Khaleel Ullah Mohammad,Dentist,14.0,"BDS, MDHM",100.0,100.0,DentiQue Dental Care,Hyderabad,10:00:00,15:00:00,Hyderabad,200.0,05:00
1526,Dr. Harshavardhan Tetala,Dentist,15.0,"Certified Implantologist, BDS",100.0,100.0,Sri Harsha Dental Clinic,Jawahar Nagar,10:30:00,14:00:00,Hyderabad,200.0,03:30
1527,Dr. Niharika Nath,Dentist,25.0,BDS,500.0,150.0,Nath Dental &a Oral Surgery Clinic,Hyderguda,10:30:00,14:00:00,Hyderabad,650.0,03:30
1528,Dr. Hasan Ahmed Omair,Dentist,13.0,Post Graduate Diploma In Hospital Administrati...,100.0,200.0,Glace Dental Care,Toli Chowki,10:00:00,14:00:00,Hyderabad,300.0,04:00
1529,Dr. Pavan Baldava,Dentist,21.0,"MDS, BDS, PGDHS IN TOBACCO CONTROL",500.0,300.0,Smilekraft Multispeciality Dental Clinic,Hyderabad,10:00:00,14:00:00,Hyderabad,800.0,04:00
1530,Dr. Duliganti Santhosh Reddy,Dentist,19.0,"BDS, MDS",0.0,200.0,DSR Sri Balaji Multispeciality LASER DENTAL HO...,Manikonda,NaT,NaT,Hyderabad,200.0,NaT
1531,Dr. Abdul Habeeb Bin Mohsin,Dentist,12.0,"MDS, Certified Implantologist, BDS, Certified ...",200.0,200.0,Dr. Abdul Habeeb Bin Mohsin,Moghalpura,17:00:00,20:00:00,Hyderabad,400.0,03:00
1532,Dr. P.Venkat Nag,Dentist,22.0,"M.Sc - Master of Oral Implantology (MOI), BDS",350.0,0.0,The Dental Specialists (on call),Banjara Hills,10:00:00,21:00:00,Hyderabad,350.0,11:00
1533,Fms Dental Hospital,Dentist,31.0,BDS (Implantologist),500.0,350.0,FMS International Dental Center - Jubilee Hills,Jubilee Hills,09:00:00,21:00:00,Hyderabad,850.0,12:00
1534,Dr. K.Arjun K,Dentist,26.0,"MDS - Oral & Maxillofacial Surgery, BDS",0.0,150.0,Tarnaka dental clinic,Tarnaka,NaT,NaT,Hyderabad,150.0,NaT
1535,Dr. Sravanthi Dubakunta,Dentist,9.0,MDS Prosthodontics,200.0,150.0,Sravanthi Dental Care,KPHB,NaT,NaT,Hyderabad,350.0,NaT
1536,Dr. Abed Ali,Dentist,22.0,BDS,100.0,0.0,Roots Multi Specialty Dental Hospital & Implan...,Kapra,10:00:00,14:00:00,Hyderabad,100.0,04:00
1537,Dr. Swathi Chaitanya,Dentist,23.0,"MDS, BDS",300.0,0.0,Vijaya Dental Hospital,Gachibowli,17:30:00,20:00:00,Hyderabad,300.0,02:30
1538,Dr. G.Viswatejashwar Rao,Dentist,16.0,"MDS, BDS, Sedation(Inhalation) Specialist",300.0,150.0,Sreehaas Dental Hospital,Madinaguda,10:00:00,18:00:00,Hyderabad,450.0,08:00
1539,Dr. Phanitej Gannamaneni,Dentist,15.0,MDS - Oral & Maxillofacial Surgery,100.0,0.0,Vishnu dental Clinic,Vanasthalipuram,09:30:00,14:00:00,Hyderabad,100.0,04:30
1540,Dr. Harish Reddy Dabala,Dentist,14.0,"MPH, BDS",300.0,500.0,PRASAD HOSPITALS,Nacharam,09:00:00,21:00:00,Hyderabad,800.0,12:00
1541,Dr. A. Rakesh Rao,Dentist,23.0,"MDS - Orthodontics , BDS",0.0,300.0,International Dental Care,Banjara Hills,10:00:00,21:00:00,Hyderabad,300.0,11:00
1542,Dr. Sanju Kumar Agarwal,Dentist,21.0,"BDS, Fellow of Academy of General Education (F...",200.0,0.0,Shiv Dental Clinic,Moosapet,10:00:00,14:00:00,Hyderabad,200.0,04:00
1543,Dr. Vandana Sangwan,Dentist,36.0,BDS,500.0,400.0,Smiline Dental Hospital,Hyderabad,09:00:00,18:00:00,Hyderabad,900.0,09:00
1544,Dr. Madhusudhan Reddy,Dentist,23.0,BDS (Implantologist),200.0,0.0,YASHAS DENTAL CLINIC,BN Reddy Nagar,08:30:00,21:00:00,Hyderabad,200.0,12:30
1545,Dr. K.Shruditha Kadevari,Dentist,20.0,BDS,200.0,200.0,Dr.K.shruditha,Domalguda,10:00:00,10:30:00,Hyderabad,400.0,00:30
1546,Dr. Satish Simha Reddy,Dentist,20.0,"MDS Prosthodontics, BDS",200.0,500.0,Siddhartha dental clinic,Yousufguda,17:30:00,21:00:00,Hyderabad,700.0,03:30
1547,Dr. Suresh Miryala,Dentist,24.0,M.D.S,100.0,200.0,SM MULTISPECIALITY DENTAL AND SKIN CLINIC,Santosh Nagar,NaT,NaT,Hyderabad,300.0,NaT
1548,Dr. Harsha Nagineni,Dentist,19.0,BDS,200.0,0.0,Harsha Dental,Chintal,10:30:00,22:00:00,Hyderabad,200.0,11:30
1549,Dr. Appaji Athota,Dentist,33.0,"M.D.S., B.D.S.",200.0,0.0,Devi Dental Clinic,Jeedimetla,10:30:00,14:00:00,Hyderabad,200.0,03:30
1550,Dr. T. Sudhakar Reddy,Dentist,25.0,"BDS, MDS Prosthodontics",150.0,0.0,Sri Sudha Dental Care,Nacharam,17:00:00,21:00:00,Hyderabad,150.0,04:00

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Available From,Available Till,City,Total Fee,Number of Hrs. Available
81,Dr. Abhijit Ray,General+Physician,13.0,M.Sc - Dietitic,700.0,300.0,Diet Home Clinic,Barrackpore,11:00:00,14:00:00,Kolkata,1000.0,03:00
82,Dr. Ayan Mukherjee,General+Physician,17.0,"B.Sc- Food & Nutrition, M.Sc- Food Science & N...",500.0,250.0,Doctors & Doctors,Sector V,11:00:00,18:30:00,Kolkata,750.0,07:30
83,Dr. Jayita Chattopadhyay,General+Physician,13.0,"Diploma in Dietetics Health & Nutrition, Post ...",500.0,350.0,Nutrizone Diet Clinic,New Alipore,10:00:00,19:00:00,Kolkata,850.0,09:00
84,Abhishek Chakrabarti,General+Physician,10.0,M.Sc - Dietitic,600.0,250.0,Bright healthcare and wellness pvt.ltd,Sakher Bazar,16:30:00,20:00:00,Kolkata,850.0,03:30
85,Dr. Mangala Roy,General+Physician,14.0,"M. SC. , B.Sc. - Dietitic",400.0,0.0,Peerless Hospital City Diagnostic Centre,Girish Park,18:00:00,19:00:00,Kolkata,400.0,01:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2042,Dr. Ramesh Rau,General+Physician,43.0,MD,400.0,0.0,Vijayshree hospital,Bangalore,17:00:00,19:00:00,Bangalore,400.0,02:00
2043,Dr. Ganesh G,General+Physician,30.0,"MBBS, F.A.G.E, D.N.B",350.0,0.0,Shree Ganesha Polyclinic,Raja Rajeshwari Nagar,09:30:00,14:30:00,Bangalore,350.0,05:00
2044,Dr. Venkatappa,General+Physician,54.0,"MBBS, MD - General Medicine",200.0,0.0,Kanwa Diagnostic Clinic,Rajaji Nagar,07:00:00,13:30:00,Bangalore,200.0,06:30
2045,Dr. M J Jayakanth,General+Physician,19.0,"MBBS, MD - General Medicine",500.0,0.0,Medicare Multispeciality Clinic And Diagnostic...,HSR Layout,09:00:00,10:00:00,Bangalore,500.0,01:00
2046,Dr. Ramesh Kn,General+Physician,30.0,MBBS Bachelor of Medicine and Bachelor of Surg...,700.0,500.0,Fortis Hospital - Cunningham,Cunningham Road,11:00:00,14:00:00,Bangalore,1200.0,03:00

In [140]:
lst = []
for i in df['Specialization'] :
    if i == 'General+Physician' :
        lst.append('General Physician')
    else :
        lst.append(i)

In [141]:
df['Specialization'] = lst

In [142]:
df['Specialization'].unique()

array(['Dentist', 'Dietitian/Nutritionist', 'General Physician',
       'Orthopedist', 'Homeopathy', 'Dermatologist', 'Gynaecologist',
       'Psychologist', 'Ayurveda'], dtype=object)

In [145]:
df.to_csv('Final Cleaned df.csv')

In [147]:
df

,Name,Specialization,Experience (in years),Education,Fee at clinic,Online Fee,Clinic Name,Area,Available From,Available Till,City,Total Fee,Number of Hrs. Available
0,Dr. Kaustubh Das,Dentist,22.0,"BDS, MFDS RCPS(Glasgow), FFD RCS (IRE)",500.0,0.0,ASPIRE CLINIC,Kolkata,10:00:00,19:00:00,Kolkata,500.0,09:00
1,Dr. Asif Naushad,Dentist,19.0,"House Surgeon, House Surgeon, House Surgeon, BDS",300.0,300.0,JM DENTAL,Kolkata,10:00:00,21:00:00,Kolkata,600.0,11:00
2,Dr. Prabhjeet Singh Sethi,Dentist,24.0,Certified Implantologist,500.0,350.0,Dontia Dental Care,Kolkata,15:00:00,20:00:00,Kolkata,850.0,05:00
3,Dr. Sanket Chakraverty,Dentist,15.0,"MDS Prosthodontics, B.D.S",300.0,300.0,Teeth Care Multispeciality Dental Clinic,Rajarhat Road,16:30:00,20:30:00,Kolkata,600.0,04:00
4,Dr. Subhajit Dutta,Dentist,13.0,BDS,500.0,300.0,SIGNATURE SMILE Dental Clinic,Kolkata,17:00:00,21:00:00,Kolkata,800.0,04:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2228,Dr. Niveditha Shree K N,Ayurveda,12.0,Bachelor of Ayurvedic Medicine & Surgery,200.0,100.0,Ashwini Ayurveda,Banashankari,18:30:00,22:00:00,Bangalore,300.0,03:30
2229,Dr. Arjun S Jogdankar,Ayurveda,10.0,"Bachelor of Ayurveda, Medicine and Surgery (BAMS)",500.0,500.0,NIROGSTREET 1VEDA MULTISPECIALITY AYURVEDA AND...,Bangalore,10:00:00,07:30:00,Bangalore,1000.0,21:30
2230,Dr. Sumedha K A,Ayurveda,11.0,"BAMS, M.D Panchakarma",300.0,200.0,Shathayu Ayurveda clinic,AECS Layout,09:00:00,19:30:00,Bangalore,500.0,10:30
2231,Dr. Prema Jyothi Fraser,Ayurveda,8.0,MD,200.0,200.0,Sri Mahima Multispecality Homoeo Clinic,Jayanagar,17:00:00,20:30:00,Bangalore,400.0,03:30
2232,Dr. Kavya Kadapi Kossambe,Ayurveda,6.0,MD - Ayurveda,300.0,300.0,Kaya chikitsalaya,ISRO Layout,10:00:00,13:00:00,Bangalore,600.0,03:00

In [149]:
twelve_hr = df[pd.to_datetime(df['Number of Hrs. Available']).dt.hour <= 12]

C:\Users\DELL\AppData\Local\Temp\ipykernel_11320\820136207.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  twelve_hr = df[pd.to_datetime(df['Number of Hrs. Available']).dt.hour <= 12]

In [153]:
twelve_hr['Number of Hrs. Available'].unique()

array(['09:00', '11:00', '05:00', '04:00', '03:00', '02:30', '06:30',
       '03:30', '04:30', '08:00', '01:00', '07:00', '06:00', '02:00',
       '01:30', '08:15', '10:00', '07:30', '10:45', '12:00', '00:00',
       '00:30', '04:15', '12:30', '11:30', '08:30', '05:30', '09:30',
       '00:15', '11:59', '02:15', '11:45', '10:30', '02:45', '10:15',
       '01:45', '06:45', '00:45', '05:31', '02:55', '06:15', '05:45',
       '05:59', '09:15', '03:03', '01:15'], dtype=object)

In [159]:
df = pd.read_csv('All cities.csv')

In [161]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2950 entries, 0 to 2949
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0.2            2950 non-null   int64
 1   Unnamed: 0              2950 non-null   int64
 2   Name                    2950 non-null   object
 3   Specialization          2950 non-null   object
 4   Experience (in years)   2777 non-null   float64
 5   Education               2665 non-null   object
 6   Fee at clinic           2181 non-null   object
 7   Online Fee              1753 non-null   object
 8   Clinic Name             2348 non-null   object
 9   Area                    2347 non-null   object
 10  Recently Consulted for  938 non-null    object
 11  Available From          2830 non-null   object
 12  Available Till          2830 non-null   object
 13  City                    2950 non-null   object
 14  Unnamed: 0.1            450 non-null    float64
dtypes: float64(2), int64(2), object(11)
memory usage: 345.8+ KB